// Oak Lodge Garden — data module
// Zones, plants (per the brief), photo paths (May + June 2026), and bed plant maps.

window.OAK = (function () {
  // ─── ZONES ────────────────────────────────────────────────────────
  // SVG coords from the brief (viewBox 820x620, ~50px = 1m)
  const ZONES = {
    bed1: {
      id: "bed1",
      title: "Flower Bed 1",
      badge: "Raised timber bed",
      dims: "2.6m × 2.6m",
      where: "Corner by the gate, upper level",
      desc:
        "Raised timber-edged bed dominated by a Japanese Maple. Layered shade-tolerant planting underneath — Fatsia, Hosta, Astilbe — with a clipped box edge.",
      shape: { kind: "rect", x: 75, y: 38, w: 130, h: 130 },
      color: "#8b5e3c",
      labelXY: [140, 105],
      plantKey: "Bed 1",
    },
    bed2: {
      id: "bed2",
      title: "Flower Bed 2",
      badge: "Long border",
      dims: "T-shape, between walls",
      where: "Lower level, west boundary",
      desc:
        "T-shaped border running between two brick walls. Weeping cherry overhangs the back, with peony, dogwood and weigela through the body. Maiden pink spills from the wall gap.",
      shape: {
        kind: "polygon",
        points: "30,250 130,250 130,335 300,335 300,395 130,395 130,475 30,475",
      },
      color: "#6b8e4e",
      labelXY: [80, 290],
      plantKey: "Bed 2",
    },
    bed3: {
      id: "bed3",
      title: "Flower Bed 3",
      badge: "Compact bed",
      dims: "0.8m × 0.8m",
      where: "Junction of steps and stone bed",
      desc:
        "Tiny pocket bed at the foot of the steps. An apple tree with bird feeders and a clump of avens.",
      shape: { kind: "rect", x: 490, y: 267, w: 40, h: 40 },
      color: "#c7a54a",
      labelXY: [510, 257],
      plantKey: "Bed 3",
    },
    bed4: {
      id: "bed4",
      title: "Flower Bed 4",
      badge: "Boundary bed",
      dims: "2m × 3.8m, mirrored L",
      where: "Right boundary wall, upper",
      desc:
        "Mirrored-L bed against the right boundary. Wisteria cascading from the wall, with phormium, yucca and lavender giving year-round structure. A climbing rose on the trellis.",
      shape: {
        kind: "polygon",
        points: "715,55 765,55 765,255 585,255 585,205 715,205",
      },
      color: "#8e6fbf",
      labelXY: [665, 140],
      plantKey: "Bed 4",
    },
    stone: {
      id: "stone",
      title: "Stone Bed",
      badge: "Gravel bed",
      dims: "≈4.8m × 1m",
      where: "Decking edge, lower level",
      desc:
        "Narrow gravel bed running along the decking edge. Mediterranean planting — houseleeks, sedum, rosemary — anchored by a Cordyline and a dark Phormium.",
      shape: { kind: "rect", x: 530, y: 267, w: 225, h: 48 },
      color: "#7a8f9a",
      labelXY: [640, 290],
      plantKey: "Stone Bed",
    },
    steps: {
      id: "steps",
      title: "Steps",
      badge: "Hardscape",
      dims: "≈3m × 3m",
      where: "Connecting upper and lower",
      desc: "Block paving with brick edging, several levels stepping down.",
      shape: { kind: "rect", x: 300, y: 260, w: 185, h: 150 },
      color: "#6e6e5e",
      labelXY: [392, 335],
    },
    patio: {
      id: "patio",
      title: "Decking",
      badge: "Composite deck",
      dims: "≈6m × 3m",
      where: "Lower level, by the house",
      desc:
        "Composite decking running along the back of the house. A mature Clematis montana climbs the left house wall.",
      shape: { kind: "rect", x: 488, y: 318, w: 277, h: 155 },
      color: "#8a7e6b",
      labelXY: [625, 395],
      plantKey: "Patio",
    },
    kitchen: {
      id: "kitchen",
      title: "Patio Kitchen",
      badge: "Outdoor room",
      dims: "1.6m × 1.4m",
      where: "Sheltered between brick walls",
      desc: "Sheltered outdoor kitchen tucked between the walls.",
      shape: { kind: "rect", x: 175, y: 400, w: 105, h: 70 },
      color: "#5c6b54",
      labelXY: [228, 435],
    },
    lounge: {
      id: "lounge",
      title: "Patio Lounge",
      badge: "Seating",
      dims: "≈3m × 1.4m",
      where: "Lower terrace, between kitchen and patio",
      desc: "Lower seating area linking kitchen to patio.",
      shape: { kind: "rect", x: 283, y: 413, w: 200, h: 60 },
      color: "#5c6b54",
      labelXY: [383, 443],
    },
    pear: {
      id: "pear",
      title: "Pear Tree",
      badge: "Specimen tree",
      dims: "Mature canopy",
      where: "Upper terrace, near gate",
      desc: "A mature pear tree on the upper terrace, near the gate.",
      shape: { kind: "rect", x: 448, y: 33, w: 64, h: 64 },
      color: "#3a6830",
      labelXY: [480, 70],
      plantKey: "Tree",
    },
    bigpot1: {
      id: "bigpot1",
      title: "Big Pot 1",
      badge: "Glazed pot",
      dims: "Large round blue pot",
      where: "Bottom of steps, by the stone bed",
      desc:
        "A large blue glazed pot at the foot of the steps, packed with summer colour — fuchsia, verbena, calibrachoa, lobelia, nepeta and a dark-sky petunia.",
      shape: { kind: "circle", cx: 508, cy: 318, r: 16 },
      color: "#2b5c9e",
      labelXY: [508, 350],
      plantKey: "Big Pot 1",
      isPot: true,
    },
    bigpot2: {
      id: "bigpot2",
      title: "Big Pot 2",
      badge: "Glazed pot",
      dims: "Large round blue pot",
      where: "Upper paving, between Bed 1 and pear tree",
      desc:
        "A large blue glazed pot on the upper paving. Lobelia, verbena, petunia, nepeta and fuchsia — the mirror planting to Big Pot 1.",
      shape: { kind: "circle", cx: 250, cy: 58, r: 16 },
      color: "#2b5c9e",
      labelXY: [250, 90],
      plantKey: "Big Pot 2",
      isPot: true,
    },
    littlepot1: {
      id: "littlepot1",
      title: "Little Pot 1",
      badge: "Small pot",
      dims: "Small square blue pot",
      where: "Top of steps, near Bed 3",
      desc:
        "A small blue pot at the top of the steps. Geranium and petunia — simple and bright.",
      shape: { kind: "circle", cx: 455, cy: 248, r: 12 },
      color: "#3a7abf",
      labelXY: [455, 230],
      plantKey: "Little Pot 1",
      isPot: true,
    },
    littlepot2: {
      id: "littlepot2",
      title: "Little Pot 2",
      badge: "Small pot",
      dims: "Small square blue pot",
      where: "Upper level, near Bed 4 entrance",
      desc:
        "A small blue pot on the upper level between the pear tree and Bed 4. Red-and-white geranium with purple-veined petunia.",
      shape: { kind: "circle", cx: 548, cy: 118, r: 12 },
      color: "#3a7abf",
      labelXY: [548, 100],
      plantKey: "Little Pot 2",
      isPot: true,
    },
    baskets: {
      id: "baskets",
      title: "Hanging Baskets",
      badge: "Front of house",
      dims: "3 baskets",
      where: "Front of house wall",
      desc:
        "Three hanging baskets on the front of the house wall. Trailing fuchsia, bacopa, lobelia and verbena — reliable summer colour from June through to the first frosts.",
      shape: { kind: "circle", cx: 625, cy: 510, r: 12 },
      color: "#c06a2a",
      labelXY: [625, 496],
      plantKey: "Baskets",
      isPot: true,
    },
  };

  // ─── PLANTS ───────────────────────────────────────────────────────
  // Care info synthesized from horticultural common knowledge per the brief.
  const PLANTS = {
    "Bed 1": [
      {
        name: "Japanese Maple",
        latin: "Acer palmatum",
        photos: ["images/plants/japanese-maple.webp", "images/plants/japanese-maple-1.webp"],
        position: "Back centre — dominant canopy",
        light: "Dappled shade to partial sun. Sheltered from harsh afternoon sun.",
        water: "Keep soil consistently moist but never waterlogged.",
        care: "Slightly acidic, well-drained loam. Mulch in spring; minimal pruning.",
        seasonal: "New leaves emerge red-bronze in April; fiery red autumn colour; bare and architectural in winter.",
      },
      {
        name: "Japanese Aralia",
        latin: "Fatsia japonica 'Spider's Web'",
        photos: ["images/plants/japanese-aralia.webp", "images/plants/japanese-aralia-2.webp", "images/plants/japanese-aralia-3.webp"],
        position: "Mid-centre, under the Acer",
        light: "Shade to partial shade. Tolerates deep shade.",
        water: "Moderate; let top inch dry between waterings.",
        care: "Rich, well-drained soil. Cut back leggy stems in spring.",
        seasonal: "Evergreen with cream-flecked leaves; cream globe flowers October–November.",
      },
      {
        name: "Rhododendron",
        latin: "Rhododendron 'Goldflimmer'",
        photos: ["images/plants/rhododendron.webp", "images/plants/rhododendron-2.webp"],
        position: "Mid-left, variegated evergreen",
        light: "Partial shade. Avoid hot, dry sun.",
        water: "Even moisture; never waterlogged.",
        care: "Acidic, ericaceous soil. Mulch with leaf mould; deadhead spent flowers.",
        seasonal: "Evergreen golden-variegated leaves year-round; lavender-purple flowers May.",
      },
      {
        name: "Astilbe",
        latin: "Astilbe",
        photos: ["images/plants/astilbe.webp"],
        position: "Right side — feathery plumes in summer",
        light: "Partial shade; tolerates more sun if soil stays moist.",
        water: "Loves moisture. Water freely in dry spells.",
        care: "Humus-rich soil. Cut back to ground in late winter.",
        seasonal: "Pink feathery plumes June–August; ferny foliage spring–autumn.",
      },
      {
        name: "Hosta",
        latin: "Hosta",
        photos: ["images/plants/hosta-patriot.webp", "images/plants/hosta-patriot-2.webp", "images/plants/hosta-francee.webp"],
        position: "Front-left, green/white variegation",
        light: "Shade to partial shade.",
        water: "Keep soil moist; mulch to retain moisture.",
        care: "Watch for slugs and snails. Divide clumps every few years.",
        seasonal: "Foliage emerges April; lilac flowers July; dies back in autumn.",
      },
      {
        name: "Angel Wings",
        latin: "Senecio candicans",
        photos: ["images/plants/angel-wings-1.webp", "images/plants/angel-wings-2.webp", "images/plants/angel-wings-3.webp"],
        position: "Front-centre — silvery-white leaves",
        light: "Full sun to partial sun.",
        water: "Drought-tolerant once established. Avoid overwatering.",
        care: "Free-draining soil. Tender — protect or lift in hard winters.",
        seasonal: "Silver-white furry leaves all season; small yellow flowers if happy.",
      },
      {
        name: "Box Hedging",
        latin: "Buxus sempervirens",
        photos: ["images/plants/box-hedging.webp", "images/plants/box-hedging-1.webp"],
        position: "Full right edge — clipped",
        light: "Sun or partial shade.",
        water: "Moderate; established plants tolerate dry spells.",
        care: "Clip twice yearly (May and August). Watch for box blight.",
        seasonal: "Evergreen year-round.",
      },
      {
        name: "Euonymus",
        latin: "Euonymus fortunei (golden)",
        photos: ["images/plants/euonymus.webp", "images/plants/euonymus-1.webp"],
        position: "Front-left corner",
        light: "Sun or partial shade.",
        water: "Moderate; very tolerant once established.",
        care: "Trim to shape in spring. Tough and trouble-free.",
        seasonal: "Golden-variegated evergreen; pink tints in cold weather.",
      },
      {
        name: "Nemesia",
        latin: "Nemesia spp.",
        photos: ["images/plants/nemesia.webp", "images/plants/nemesia-1.webp", "images/plants/nemesia-2.webp"],
        position: "Front edge — orange/coral",
        light: "Full sun.",
        water: "Moderate; don't let pots dry out.",
        care: "Deadhead and trim back to keep flowering.",
        seasonal: "Continuous flowers May–October.",
      },
      {
        name: "Hardy Geranium",
        latin: "Geranium spp.",
        photos: ["images/plants/hardy-geranium.webp"],
        position: "Front-right — spreading low clumps",
        light: "Sun to partial shade. Very adaptable.",
        water: "Low to moderate once established.",
        care: "Cut back hard after first flush for a second showing. Divide every 3–4 years.",
        seasonal: "Deeply lobed foliage from April; purple-blue flowers May–July, often a second flush in autumn.",
      },
      {
        name: "Wintercreeper",
        latin: "Euonymus fortunei",
        photos: ["images/plants/wintercreeper.webp", "images/plants/wintercreeper-silver-queen.webp", "images/plants/wintercreeper-3.webp"],
        position: "Front-right — spreading variegated evergreen",
        light: "Sun or partial shade.",
        water: "Moderate.",
        care: "Trim to shape in spring. Very tough and low-care.",
        seasonal: "Evergreen white-and-green leaves year-round; pink tints in cold weather.",
      },
      {
        name: "Dahlia",
        latin: "Dahlia (dark-leaved, Bishop type)",
        photos: ["images/plants/dahlia-1.webp", "images/plants/dahlia-2.webp", "images/plants/dahlia-3.webp"],
        position: "Centre — dark foliage, red flowers to come",
        light: "Full sun. Needs warmth to thrive.",
        water: "Regular watering, especially in dry spells. Don't let soil dry out completely.",
        care: "Rich, well-drained soil. Mulch the crown. Stake if it gets tall. Lift tubers in autumn or mulch heavily for winter protection. Pinch out the growing tip early to encourage bushiness. Deadhead spent flowers for continuous blooming.",
        seasonal: "Dark bronze-black foliage from May; red flowers July–October; dies back after first hard frost. Tubers overwinter underground with protection.",
      },
    ],
    "Bed 2": [
      {
        name: "Weeping Cherry",
        latin: "Prunus species",
        photos: ["images/plants/weeping-cherry.webp", "images/plants/weeping-cherry-1.webp", "images/plants/weeping-cherry-2.webp"],
        position: "Upper section — overhanging the wall",
        light: "Full sun.",
        water: "Moderate; deep watering when young.",
        care: "Light pruning after flowering; avoid heavy cuts.",
        seasonal: "Pink blossom April; green canopy summer; bare winter.",
      },
      {
        name: "Variegated Dogwood",
        latin: "Cornus alba 'Elegantissima'",
        photos: ["images/plants/variegated-dogwood.webp"],
        position: "Upper section — red winter stems",
        light: "Sun or partial shade.",
        water: "Moisture-loving; tolerates wet soil.",
        care: "Cut a third of stems to ground each March for best winter colour.",
        seasonal: "Cream-edged leaves spring–autumn; brilliant red stems winter.",
      },
      {
        name: "Peony",
        latin: "Paeonia lactiflora",
        photos: ["images/plants/peony.webp"],
        position: "Lower section",
        light: "Full sun, sheltered.",
        water: "Moderate; deep watering when budding.",
        care: "Don't bury the crown. Stake floppy heads. Resents being moved.",
        seasonal: "Huge fragrant flowers May–June; foliage to ground in autumn.",
      },
      {
        name: "Weigela",
        latin: "Weigela florida",
        photos: ["images/plants/weigela.webp"],
        position: "Mid section",
        light: "Full sun.",
        water: "Moderate.",
        care: "Prune one in three old stems after flowering.",
        seasonal: "Pink trumpet flowers May–June; sometimes a second flush.",
      },
      {
        name: "Silverbush",
        latin: "Convolvulus cneorum",
        photos: ["images/plants/silverbush.webp", "images/plants/silverbush-2.webp", "images/plants/silverbush-3.webp"],
        position: "Mid-right — silvery foliage",
        light: "Full sun.",
        water: "Drought-tolerant. Hates wet feet.",
        care: "Sharp drainage essential. Light trim after flowering.",
        seasonal: "White trumpet flowers May–September on silver mound.",
      },
      {
        name: "Hosta",
        latin: "Hosta",
        photos: ["images/plants/hosta-gold-standard.webp"],
        position: "Lower, next to Weigela",
        light: "Shade to partial shade.",
        water: "Keep moist.",
        care: "Slug protection; divide every few years.",
        seasonal: "Emerges April; lilac flowers July.",
      },
      {
        name: "Angel Wings",
        latin: "Senecio candicans",
        photos: ["images/plants/angel-wings-1.webp", "images/plants/angel-wings-2.webp", "images/plants/angel-wings-3.webp"],
        position: "Lower, front",
        light: "Full sun.",
        water: "Drought-tolerant.",
        care: "Free-draining soil; tender in hard winters.",
        seasonal: "Silver foliage all season.",
      },
      {
        name: "Kerria",
        latin: "Kerria japonica",
        photos: ["images/plants/kerria.webp", "images/plants/kerria-1.webp"],
        position: "Against the wall — arching stems with yellow flowers",
        light: "Partial shade to full sun.",
        water: "Low to moderate. Tolerates dry shade.",
        care: "Cut flowered stems back to the base after flowering. Remove all-green suckers promptly.",
        seasonal: "Bright single yellow flowers April–May; arching green stems attractive all year.",
      },
      {
        name: "Forget-me-not",
        latin: "Myosotis",
        photos: ["images/plants/forget-me-not.webp"],
        position: "Lower — small blue flowers",
        light: "Sun to partial shade.",
        water: "Moderate.",
        care: "Biennial; lets itself seed about. Pull spent plants in summer.",
        seasonal: "Sky-blue clouds April–June.",
      },
      {
        name: "Maiden Pink",
        latin: "Dianthus deltoides",
        photos: ["images/plants/maiden-pink.webp"],
        position: "Between walls — pink flowers",
        light: "Full sun.",
        water: "Low; sharp drainage.",
        care: "Trim after flowering. Mat-forming.",
        seasonal: "Pink stars June–August.",
      },
      {
        name: "Garden Pink",
        latin: "Dianthus plumarius",
        photos: ["images/plants/dianthus.webp", "images/plants/dianthus-1.webp", "images/plants/dianthus-2.webp"],
        position: "Lower front — compact fragrant mound",
        light: "Full sun.",
        water: "Low. Sharp drainage essential.",
        care: "Deadhead to extend flowering. Cut back after main flush. Replace plants every 3 years as they become woody.",
        seasonal: "Fragrant double pink flowers June–August; silver-grey cushion foliage year-round.",
      },
      {
        name: "Centaurea 'Snowy Owl'",
        latin: "Centaurea montana 'Snowy Owl'",
        position: "Against the wall — white cornflower flowers",
        light: "Full sun.",
        water: "Low to moderate.",
        care: "Cut back after flowering for a second flush. Short-lived perennial; divide every 2–3 years.",
        seasonal: "White cornflower blooms May–July; ferny silver-green foliage.",
      },
      {
        name: "Hydrangea petiolaris",
        latin: "Hydrangea anomala subsp. petiolaris",
        position: "Against the far wall — self-clinging climber",
        light: "Partial shade to full shade. Tolerates north-facing walls.",
        water: "Moist but well-drained.",
        care: "Slow to establish; once settled it is vigorous. Light prune to shape after flowering.",
        seasonal: "White lace-cap flowers June–July; golden autumn leaf colour; interesting bark in winter.",
      },
      {
        name: "Red Hot Poker",
        latin: "Kniphofia",
        position: "Lower section — torch-like flower spikes to come",
        light: "Full sun.",
        water: "Moderate; drought-tolerant once established.",
        care: "Cut back old foliage in spring. Mulch crown in cold winters. Clump-forming — divide every 4–5 years.",
        seasonal: "Bold orange-red poker spikes July–September; evergreen grassy foliage.",
      },
      {
        name: "Euonymus 'Emerald Gaiety'",
        latin: "Euonymus fortunei 'Emerald Gaiety'",
        position: "Lower section — spreading, white-margined leaves",
        light: "Sun or partial shade.",
        water: "Moderate; tolerates dry spells once established.",
        care: "Trim to shape in spring. Very hardy and low-maintenance. Moved from Bed 3, June 2026.",
        seasonal: "Evergreen white-margined leaves year-round; pink blush to the margins in cold spells.",
      },
    ],
    "Bed 3": [
      {
        name: "Apple Tree",
        latin: "Malus domestica",
        photos: ["images/plants/apple-tree.webp", "images/plants/apple-tree-1.webp"],
        position: "Centre — with bird feeders",
        light: "Full sun.",
        water: "Deep watering in dry spells, especially when fruiting.",
        care: "Winter prune for shape. Thin fruit in June for size.",
        seasonal: "Blossom April; fruit August–October; bare winter.",
      },
      {
        name: "Avens",
        latin: "Geum",
        photos: ["images/plants/avens-orange.webp", "images/plants/avens-red-orange.webp", "images/plants/avens-orange-2.webp", "images/plants/avens-orange-3.webp"],
        position: "Front-left — orange flowers",
        light: "Sun or partial shade.",
        water: "Moderate.",
        care: "Deadhead. Divide every few years.",
        seasonal: "Orange flowers May–July, often a second flush.",
      },
    ],
    "Bed 4": [
      {
        name: "Wisteria",
        latin: "Wisteria spp.",
        photos: ["images/plants/wisteria.webp", "images/plants/wisteria-1.webp", "images/plants/wisteria-2.webp"],
        position: "Top — cascading over the wall",
        light: "Full sun.",
        water: "Deep watering when young; established plants tolerate drought.",
        care: "Prune twice yearly: August (long shoots to 6 leaves) and February (back to 2–3 buds).",
        seasonal: "Lilac racemes May; bare gnarled stems winter.",
      },
      {
        name: "Rose",
        latin: "Rosa",
        photos: ["images/plants/rose.webp"],
        position: "Mid — on trellis/support",
        light: "Full sun.",
        water: "Deep watering, mulch in spring.",
        care: "Prune in late winter. Feed in spring and after first flush.",
        seasonal: "Flowers June–September; bare winter.",
      },
      {
        name: "Yucca",
        latin: "Yucca filamentosa",
        photos: ["images/plants/yucca.webp", "images/plants/yucca-1.webp"],
        position: "Lower-left — spiky, architectural",
        light: "Full sun.",
        water: "Drought-tolerant.",
        care: "Free-draining soil. Almost indestructible.",
        seasonal: "Evergreen; spire of white bell flowers in summer when mature.",
      },
      {
        name: "Lavender",
        latin: "Lavandula angustifolia",
        photos: ["images/plants/lavender.webp", "images/plants/lavender-1.webp"],
        position: "Right — grey-green foliage",
        light: "Full sun.",
        water: "Drought-tolerant.",
        care: "Trim lightly after flowering and again in spring. Don't cut into old wood.",
        seasonal: "Purple flower spikes June–August; aromatic year-round.",
      },
    ],
    "Stone Bed": [
      {
        name: "Houseleeks",
        latin: "Sempervivum",
        photos: ["images/plants/houseleek.webp"],
        position: "Left-centre — rosettes in gravel",
        light: "Full sun.",
        water: "Very low. Hates wet.",
        care: "Sharp drainage; almost no maintenance.",
        seasonal: "Evergreen rosettes; flowering rosettes die after blooming, replaced by offsets.",
      },
      {
        name: "Stonecrop",
        latin: "Sedum (trailing)",
        photos: ["images/plants/stonecrop-1.webp", "images/plants/stonecrop-2.webp", "images/plants/stonecrop-3.webp"],
        position: "Centre-left",
        light: "Full sun.",
        water: "Low.",
        care: "Free-draining soil. Cut back in late winter.",
        seasonal: "Foliage year-round; flowers summer–autumn.",
      },
      {
        name: "New Zealand Flax (dark)",
        latin: "Phormium 'Platt's Black'",
        photos: ["images/plants/phormium.webp", "images/plants/phormium-1.webp"],
        position: "Centre — dark burgundy spikes",
        light: "Full sun.",
        water: "Moderate; drought-tolerant once established.",
        care: "Remove old leaves at base. Architectural and low-care.",
        seasonal: "Evergreen dark foliage year-round.",
      },
      {
        name: "Rosemary",
        latin: "Salvia rosmarinus",
        photos: ["images/plants/rosemary.webp"],
        position: "Centre-right — grey-green needles",
        light: "Full sun.",
        water: "Low.",
        care: "Sharp drainage. Light trim after flowering.",
        seasonal: "Evergreen aromatic; pale blue flowers spring.",
      },
      {
        name: "Cabbage Tree",
        latin: "Cordyline australis 'Red Star'",
        photos: ["images/plants/cordyline.webp"],
        position: "Right — large palm-like tree",
        light: "Full sun.",
        water: "Moderate; established plants tolerate drought.",
        care: "Tie up leaves in winter to protect crown if hard frost forecast.",
        seasonal: "Evergreen burgundy fountain of leaves.",
      },
      {
        name: "Hebe",
        latin: "Hebe (syn. Veronica) cultivar",
        photos: ["images/plants/hebe.webp"],
        position: "Stone Bed — variegated foliage shrub",
        light: "Full sun to partial shade.",
        water: "Moderate. Good drainage. Dislikes waterlogging.",
        care: "Light trim after flowering. Not fully hardy — protect in prolonged hard frosts. Note: botanically reclassified from Hebe to Veronica, though widely sold under both names. Visual traits suggest 'Heartbreaker' or a closely related variegated cultivar.",
        seasonal: "Evergreen variegated foliage year-round; small purple-white flower spikes in summer.",
      },
    ],
    Patio: [
      {
        name: "Honeysuckle",
        latin: "Lonicera",
        photos: ["images/plants/honeysuckle.webp", "images/plants/honeysuckle-1.webp", "images/plants/honeysuckle-2.webp"],
        position: "Far right — climbing on support",
        light: "Sun, with shaded roots.",
        water: "Moderate.",
        care: "Light prune after flowering. Train onto support.",
        seasonal: "Fragrant flowers June–August.",
      },
      {
        name: "Clematis",
        latin: "Clematis montana",
        photos: ["images/plants/clematis.webp"],
        position: "Left side of house wall — mature woody stems",
        light: "Sun, with shaded roots.",
        water: "Moderate.",
        care: "Group 1 clematis — light prune after flowering only. Tie in new growth.",
        seasonal: "Sheets of pale pink flowers May; vigorous summer growth.",
      },
    ],
    Tree: [
      {
        name: "Pear Tree",
        latin: "Pyrus",
        photos: ["images/plants/pear-tree.webp", "images/plants/pear-tree-1.webp", "images/plants/pear-tree-2.webp"],
        position: "Upper terrace — near the gate",
        light: "Full sun.",
        water: "Deep watering in dry summers.",
        care: "Winter prune for shape. Thin fruit if heavy.",
        seasonal: "White blossom April; fruit September; bare winter.",
      },
    ],
    "Big Pot 1": [
      {
        name: "Fuchsia",
        latin: "Fuchsia 'Mrs Popple'",
        photos: ["images/plants/big-pot-1.webp", "images/plants/big-pot-1-2.webp"],
        position: "Back centre — upright",
        light: "Partial shade to full sun.",
        water: "Keep compost moist. Water daily in hot weather.",
        care: "Hardy bush fuchsia. Cut back hard in spring. Feed fortnightly through summer.",
        seasonal: "Red and purple pendant flowers June–October; deciduous in winter; new growth from the base in spring.",
      },
      {
        name: "Verbena",
        latin: "Verbena 'Showboat Light Pink'",
        photos: ["images/plants/big-pot-1.webp"],
        position: "Front-left — trailing clusters",
        light: "Full sun.",
        water: "Regular; don't let compost dry out.",
        care: "Deadhead to keep flowering. Tender annual — replace yearly.",
        seasonal: "Clusters of soft pink flowers June–October.",
      },
      {
        name: "Calibrachoa",
        latin: "Calibrachoa 'Cabaret Special Pink Star'",
        photos: ["images/plants/big-pot-1.webp"],
        position: "Front — trailing",
        light: "Full sun.",
        water: "Keep evenly moist. Hates drying out.",
        care: "Feed weekly with liquid tomato food. Tender annual.",
        seasonal: "Pink star-patterned flowers May–October. Continuous if fed.",
      },
      {
        name: "Nepeta",
        latin: "Nepeta (catmint)",
        photos: ["images/plants/big-pot-1.webp"],
        position: "Mid — aromatic foliage",
        light: "Full sun.",
        water: "Low to moderate. Drought-tolerant once established.",
        care: "Cut back after first flush for a repeat. Aromatic — cats love it.",
        seasonal: "Lavender-blue spikes June–September; grey-green aromatic foliage.",
      },
      {
        name: "Lobelia",
        latin: "Lobelia 'Waterfall Deep Blue Ice'",
        photos: ["images/plants/big-pot-1.webp"],
        position: "Edge — trailing cascade",
        light: "Partial shade to full sun.",
        water: "Keep moist at all times. Hates drying out.",
        care: "Trim back leggy growth mid-season. Tender annual.",
        seasonal: "Deep blue and white trailing flowers May–October.",
      },
      {
        name: "Petunia",
        latin: "Petunia 'Midnight Sky'",
        photos: ["images/plants/big-pot-1.webp"],
        position: "Front-right — dark purple trumpet flowers",
        light: "Full sun.",
        water: "Regular; don't let compost dry out completely.",
        care: "Deadhead spent blooms. Feed weekly. Tender annual.",
        seasonal: "Dark purple-white trumpet flowers May–October.",
      },
    ],
    "Big Pot 2": [
      {
        name: "Lobelia",
        latin: "Lobelia 'Waterfall Deep Blue Ice'",
        photos: ["images/plants/big-pot-2.webp", "images/plants/big-pot-2-2.webp"],
        position: "Edge — trailing cascade",
        light: "Partial shade to full sun.",
        water: "Keep moist at all times. Hates drying out.",
        care: "Trim back leggy growth mid-season. Tender annual.",
        seasonal: "Deep blue and white trailing flowers May–October.",
      },
      {
        name: "Verbena",
        latin: "Verbena 'Venturi Pink Bicolour'",
        photos: ["images/plants/big-pot-2.webp"],
        position: "Front — pink and white clusters",
        light: "Full sun.",
        water: "Regular; don't let compost dry out.",
        care: "Deadhead to keep flowering. Tender annual.",
        seasonal: "Pink bicolour flower clusters June–October.",
      },
      {
        name: "Petunia",
        latin: "Petunia 'Sky Purple White Sky'",
        photos: ["images/plants/big-pot-2.webp"],
        position: "Front — purple and white trumpets",
        light: "Full sun.",
        water: "Regular; don't let compost dry out completely.",
        care: "Deadhead spent blooms. Feed weekly. Tender annual.",
        seasonal: "Purple-white striped trumpet flowers May–October.",
      },
      {
        name: "Nepeta",
        latin: "Nepeta (catmint)",
        photos: ["images/plants/big-pot-2.webp"],
        position: "Mid — aromatic foliage",
        light: "Full sun.",
        water: "Low to moderate. Drought-tolerant once established.",
        care: "Cut back after first flush for a repeat. Aromatic.",
        seasonal: "Lavender-blue spikes June–September; grey-green aromatic foliage.",
      },
      {
        name: "Fuchsia",
        latin: "Fuchsia 'Mrs Popple'",
        photos: ["images/plants/big-pot-2.webp"],
        position: "Back centre — upright",
        light: "Partial shade to full sun.",
        water: "Keep compost moist. Water daily in hot weather.",
        care: "Hardy bush fuchsia. Cut back hard in spring. Feed fortnightly through summer.",
        seasonal: "Red and purple pendant flowers June–October; deciduous in winter.",
      },
    ],
    "Little Pot 1": [
      {
        name: "Geranium",
        latin: "Pelargonium 'Trend Sophie Dark Red'",
        photos: ["images/plants/little-pot-1.webp"],
        position: "Back — upright dark red flowers",
        light: "Full sun.",
        water: "Moderate. Let compost dry slightly between waterings.",
        care: "Deadhead regularly. Feed fortnightly. Not frost-hardy — overwinter indoors or treat as annual.",
        seasonal: "Dark red flower heads May–October; scented rounded leaves.",
      },
      {
        name: "Petunia",
        latin: "Petunia 'Vivini Blue Star'",
        photos: ["images/plants/little-pot-1.webp"],
        position: "Front — blue and white star pattern",
        light: "Full sun.",
        water: "Regular; don't let compost dry out completely.",
        care: "Deadhead spent blooms. Feed weekly. Tender annual.",
        seasonal: "Blue-white star-patterned flowers May–October.",
      },
    ],
    "Little Pot 2": [
      {
        name: "Geranium",
        latin: "Pelargonium 'Summer Twist Red White'",
        photos: ["images/plants/little-pot-2.webp"],
        position: "Back — red and white bicolour flowers",
        light: "Full sun.",
        water: "Moderate. Let compost dry slightly between waterings.",
        care: "Deadhead regularly. Feed fortnightly. Not frost-hardy — overwinter indoors or treat as annual.",
        seasonal: "Red-white bicolour flower heads May–October; rounded leaves.",
      },
      {
        name: "Petunia",
        latin: "Petunia 'Purple Vein'",
        photos: ["images/plants/little-pot-2.webp"],
        position: "Front — purple veined trumpets",
        light: "Full sun.",
        water: "Regular; don't let compost dry out completely.",
        care: "Deadhead spent blooms. Feed weekly. Tender annual.",
        seasonal: "Purple-veined trumpet flowers May–October.",
      },
    ],
    "Baskets": [
      {
        name: "Trailing Fuchsia",
        latin: "Fuchsia (trailing cultivar)",
        position: "Main trailing plant",
        light: "Partial shade to full sun.",
        water: "Daily in hot weather; never let dry out completely.",
        care: "Feed weekly. Deadhead spent flowers. Not frost-hardy — replace each year.",
        seasonal: "Pendant bicolour flowers June–October.",
      },
      {
        name: "Bacopa",
        latin: "Sutera cordata",
        position: "Trailing filler",
        light: "Sun to partial shade.",
        water: "Keep evenly moist.",
        care: "Self-cleaning; no deadheading needed. Trim back if leggy. Tender annual.",
        seasonal: "Tiny white flowers May–October; neat trailing habit.",
      },
      {
        name: "Trailing Lobelia",
        latin: "Lobelia erinus (trailing)",
        position: "Trailing — blue cascade",
        light: "Sun to partial shade.",
        water: "Keep moist; hates drying out.",
        care: "Trim back mid-season if it gets straggly. Tender annual.",
        seasonal: "Blue trailing flowers May–October.",
      },
      {
        name: "Trailing Verbena",
        latin: "Verbena (trailing cultivar)",
        position: "Trailing — mixed colours",
        light: "Full sun.",
        water: "Regular; don't let dry out.",
        care: "Deadhead to extend flowering. Tender annual.",
        seasonal: "Clusters of flowers June–October.",
      },
    ],
  };

  // ─── PHOTOS (by month) ────────────────────────────────────────────
  const PHOTOS_BY_MONTH = {
    "may-2026": {
      label: "May 2026",
      bed1: [
        { src: "images/may-2026/bed1.jpg",        caption: "Overview from paving" },
        { src: "images/may-2026/bed1-close1.jpg",  caption: "Japanese Maple area" },
        { src: "images/may-2026/bed1-close2.jpg",  caption: "Front planting" },
        { src: "images/may-2026/bed1-3.webp",      caption: "From above" },
        { src: "images/may-2026/bed1-4.webp",      caption: "From upper terrace" },
        { src: "images/may-2026/bed1-wide.webp",   caption: "Wide shot from street" },
        { src: "images/may-2026/bed1-wide-2.webp", caption: "From gate, angle 2" },
        { src: "images/may-2026/bed1-maple.webp",  caption: "Japanese Maple from street" },
        { src: "images/may-2026/bed1-close3.webp", caption: "Box edging detail" },
        { src: "images/may-2026/bed1-7.webp",      caption: "Box hedging close" },
        { src: "images/plants/dahlia-1.webp",       caption: "Dahlia — dark-leaved, newly planted" },
        { src: "images/plants/dahlia-2.webp",       caption: "Dahlia — close-up of foliage" },
        { src: "images/plants/dahlia-3.webp",       caption: "Dahlia — from above" },
      ],
      bed2: [
        { src: "images/may-2026/bed2-1.jpg",       caption: "Overview, angle 1" },
        { src: "images/may-2026/bed2-2.jpg",       caption: "Overview, angle 2" },
        { src: "images/may-2026/bed2-kitchen.jpg", caption: "From the patio kitchen" },
        { src: "images/may-2026/bed2-steps.jpg",   caption: "From the steps" },
        { src: "images/may-2026/bed2-south1.jpg",  caption: "South angle 1" },
        { src: "images/may-2026/bed2-south2.jpg",  caption: "South angle 2" },
        { src: "images/may-2026/bed2-wide.webp",   caption: "Wide overview" },
        { src: "images/may-2026/bed2-3.webp",      caption: "From lower paving" },
        { src: "images/may-2026/bed2-4.webp",      caption: "Steps side" },
        { src: "images/may-2026/bed2-5.webp",      caption: "Lower angle" },
        { src: "images/may-2026/bed2-6.webp",      caption: "From patio" },
      ],
      bed3: [
        { src: "images/may-2026/bed3.jpg",         caption: "Apple tree & avens" },
        { src: "images/may-2026/bed3-detail.jpg",  caption: "From lower paving" },
        { src: "images/may-2026/bed3-3.webp",      caption: "Apple tree & bird feeders" },
      ],
      bed4: [
        { src: "images/may-2026/bed4.jpg",         caption: "Wisteria overview" },
        { src: "images/may-2026/bed4-wide.jpg",    caption: "Wider angle" },
        { src: "images/may-2026/bed4-3.webp",      caption: "Wisteria in full flower" },
      ],
      stone: [
        { src: "images/may-2026/stone-bed.jpg",         caption: "Overview" },
        { src: "images/may-2026/stone-bed-wide.jpg",    caption: "From the patio" },
        { src: "images/may-2026/stone-bed-detail1.jpg", caption: "Phormium & houseleeks" },
        { src: "images/may-2026/stone-bed-detail2.jpg", caption: "Cordyline Red Star" },
        { src: "images/may-2026/stone-bed-5.webp",      caption: "Stone bed & decking" },
        { src: "images/may-2026/stone-bed-6.webp",      caption: "From above" },
        { src: "images/may-2026/stone-bed-wide-2.webp", caption: "Wide, from patio" },
        { src: "images/may-2026/stone-bed-7.webp",      caption: "With Cordyline" },
      ],
      patio: [
        { src: "images/may-2026/patio.jpg",            caption: "Decking" },
        { src: "images/may-2026/patio-door.jpg",       caption: "Towards the house" },
        { src: "images/may-2026/patio-clematis.jpg",   caption: "Clematis montana" },
        { src: "images/may-2026/patio-2.webp",         caption: "Circular paving" },
        { src: "images/may-2026/patio-3.webp",         caption: "Decking full length" },
      ],
      steps: [
        { src: "images/may-2026/steps.jpg",        caption: "Steps between levels" },
        { src: "images/may-2026/steps-2.webp",     caption: "Steps from front" },
        { src: "images/may-2026/steps-wide.webp",  caption: "Wide view from above" },
        { src: "images/may-2026/steps-3.webp",     caption: "Upper terrace looking down" },
      ],
      kitchen: [],
      lounge: [
        { src: "images/may-2026/lounge.webp", caption: "Side passage" },
      ],
      pear: [
        { src: "images/may-2026/pear-2.webp", caption: "Upper garden overview" },
      ],
      bigpot1: [
        { src: "images/plants/big-pot-1.webp",   caption: "Big Pot 1 — overview" },
        { src: "images/plants/big-pot-1-2.webp", caption: "Big Pot 1 — from above" },
      ],
      bigpot2: [
        { src: "images/plants/big-pot-2.webp",   caption: "Big Pot 2 — overview" },
        { src: "images/plants/big-pot-2-2.webp", caption: "Big Pot 2 — from above" },
      ],
      littlepot1: [
        { src: "images/plants/little-pot-1.webp", caption: "Little Pot 1 — geranium & petunia" },
      ],
      littlepot2: [
        { src: "images/plants/little-pot-2.webp", caption: "Little Pot 2 — geranium & petunia" },
      ],
      baskets: [],
    },
    "june-2026": {
      label: "June 2026",
      bed1: [
        { src: "images/june-2026/japanese-maple.webp",  caption: "Japanese Maple — full summer canopy" },
        { src: "images/june-2026/hosta-bed1-1.webp",    caption: "Hosta — Bed 1" },
        { src: "images/june-2026/hosta-bed1-2.webp",    caption: "Hosta — close-up" },
        { src: "images/june-2026/dahlia-context.webp",  caption: "Dahlia in context" },
        { src: "images/june-2026/dahlia.webp",          caption: "Dahlia — close-up of foliage" },
        { src: "images/june-2026/angel-wings.webp",     caption: "Angel Wings" },
        { src: "images/june-2026/euonymus.webp",        caption: "Euonymus" },
        { src: "images/june-2026/fatsia.webp",          caption: "Fatsia japonica" },
        { src: "images/june-2026/astilbe-1.webp",       caption: "Astilbe — flower spike emerging" },
        { src: "images/june-2026/astilbe-2.webp",       caption: "Astilbe — foliage close-up" },
      ],
      bed2: [
        { src: "images/june-2026/centaurea-snowy-owl-1.webp", caption: "Centaurea 'Snowy Owl'" },
        { src: "images/june-2026/centaurea-snowy-owl-2.webp", caption: "Centaurea — close-up" },
        { src: "images/june-2026/silverbush.webp",            caption: "Silverbush" },
        { src: "images/june-2026/maiden-pink.webp",           caption: "Maiden Pink" },
        { src: "images/june-2026/variegated-dogwood.webp",    caption: "Variegated Dogwood" },
        { src: "images/june-2026/hydrangea-petiolaris.webp",  caption: "Hydrangea petiolaris — newly identified" },
        { src: "images/june-2026/peony.webp",                 caption: "Peony" },
        { src: "images/june-2026/hosta-bed2.webp",            caption: "Hosta — Bed 2" },
        { src: "images/june-2026/weigela.webp",               caption: "Weigela" },
        { src: "images/june-2026/red-hot-poker.webp",         caption: "Red Hot Poker — not yet flowered" },
        { src: "images/june-2026/weeping-cherry-june-1.webp", caption: "Weeping Cherry — full summer canopy" },
        { src: "images/june-2026/weeping-cherry-june-2.webp", caption: "Weeping Cherry — wide shot" },
        { src: "images/june-2026/forget-me-not.webp",         caption: "Forget-me-not" },
        { src: "images/june-2026/euonymus-emerald-gaiety.webp", caption: "Euonymus 'Emerald Gaiety' — newly moved from Bed 3" },
      ],
      bed3: [
        { src: "images/june-2026/apple-tree.webp", caption: "Apple Tree" },
        { src: "images/june-2026/avens-1.webp",    caption: "Avens — orange flowers" },
        { src: "images/june-2026/avens-2.webp",    caption: "Avens — close-up" },
        { src: "images/june-2026/avens-3.webp",    caption: "Avens — cluster" },
        { src: "images/june-2026/avens-4.webp",    caption: "Avens — wide" },
      ],
      bed4: [
        { src: "images/june-2026/wisteria.webp", caption: "Wisteria" },
        { src: "images/june-2026/rose.webp",     caption: "Rose" },
        { src: "images/june-2026/lavender.webp", caption: "Lavender" },
        { src: "images/june-2026/yucca.webp",    caption: "Yucca" },
      ],
      stone: [
        { src: "images/june-2026/cordyline-1.webp",   caption: "Cordyline" },
        { src: "images/june-2026/cordyline-2.webp",   caption: "Cordyline — mid-shot" },
        { src: "images/june-2026/cordyline-3.webp",   caption: "Cordyline — close-up" },
        { src: "images/june-2026/houseleeks-1.webp",  caption: "Houseleeks" },
        { src: "images/june-2026/houseleeks-2.webp",  caption: "Houseleeks — rosettes" },
        { src: "images/june-2026/stonecrop-1.webp",   caption: "Stonecrop" },
        { src: "images/june-2026/stonecrop-2.webp",   caption: "Stonecrop — mid-shot" },
        { src: "images/june-2026/stonecrop-3.webp",   caption: "Stonecrop — close-up" },
        { src: "images/june-2026/phormium-dark.webp", caption: "Dark Phormium" },
        { src: "images/june-2026/rosemary.webp",      caption: "Rosemary" },
      ],
      patio: [
        { src: "images/june-2026/honeysuckle-1.webp", caption: "Honeysuckle" },
        { src: "images/june-2026/honeysuckle-2.webp", caption: "Honeysuckle — flowers" },
        { src: "images/june-2026/clematis.webp",      caption: "Clematis montana" },
      ],
      steps: [],
      kitchen: [],
      lounge: [],
      pear: [
        { src: "images/june-2026/pear-tree.webp", caption: "Pear Tree — June" },
      ],
      bigpot1: [
        { src: "images/june-2026/big-pot-1-wide.webp", caption: "Big Pot 1 — wide" },
        { src: "images/june-2026/big-pot-1.webp",      caption: "Big Pot 1" },
      ],
      bigpot2: [
        { src: "images/june-2026/big-pot-2-wide.webp", caption: "Big Pot 2 — wide" },
        { src: "images/june-2026/big-pot-2.webp",      caption: "Big Pot 2" },
      ],
      littlepot1: [
        { src: "images/june-2026/little-pot-1-wide.webp", caption: "Little Pot 1 — wide" },
        { src: "images/june-2026/little-pot-1.webp",      caption: "Little Pot 1" },
      ],
      littlepot2: [
        { src: "images/june-2026/little-pot-2.webp", caption: "Little Pot 2" },
      ],
      baskets: [
        { src: "images/june-2026/hanging-basket-1.webp", caption: "Hanging Basket — front of house" },
        { src: "images/june-2026/hanging-basket-2.webp", caption: "Hanging Basket — close-up" },
      ],
    },
  };

  // ─── PLANT PHOTOS ─────────────────────────────────────────────────
  // Per-plant photo journal. Keyed by plant name, newest month first.
  // Each entry: { month, label, photos: [{src, caption}] }
  const PLANT_PHOTOS = {
    "Japanese Maple": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/japanese-maple.webp", caption: "Full summer canopy" }] },
      { month: "may-2026",  label: "May 2026",  photos: [{ src: "images/may-2026/bed1-close1.jpg",      caption: "Japanese Maple area" }] },
    ],
    "Japanese Aralia": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/fatsia.webp", caption: "Fatsia japonica" }] },
    ],
    "Dahlia": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/dahlia-context.webp", caption: "In context" },
        { src: "images/june-2026/dahlia.webp",         caption: "Close-up of dark foliage" },
      ]},
    ],
    "Angel Wings": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/angel-wings.webp", caption: "Angel Wings — silvery leaves" }] },
    ],
    "Euonymus": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/euonymus.webp", caption: "Euonymus — golden foliage" }] },
    ],
    "Hosta": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/hosta-bed1-1.webp", caption: "Hosta — Bed 1" },
        { src: "images/june-2026/hosta-bed1-2.webp", caption: "Hosta — Bed 1, close-up" },
        { src: "images/june-2026/hosta-bed2.webp",   caption: "Hosta — Bed 2" },
      ]},
    ],
    "Weeping Cherry": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/weeping-cherry-june-1.webp", caption: "Full summer canopy" },
        { src: "images/june-2026/weeping-cherry-june-2.webp", caption: "Wide shot" },
      ]},
    ],
    "Variegated Dogwood": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/variegated-dogwood.webp", caption: "Variegated Dogwood" }] },
    ],
    "Peony": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/peony.webp", caption: "Peony — full bloom" }] },
    ],
    "Weigela": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/weigela.webp", caption: "Weigela" }] },
    ],
    "Silverbush": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/silverbush.webp", caption: "Silverbush in flower" }] },
    ],
    "Maiden Pink": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/maiden-pink.webp", caption: "Maiden Pink" }] },
    ],
    "Centaurea 'Snowy Owl'": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/centaurea-snowy-owl-1.webp", caption: "Centaurea 'Snowy Owl'" },
        { src: "images/june-2026/centaurea-snowy-owl-2.webp", caption: "Close-up" },
      ]},
    ],
    "Hydrangea petiolaris": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/hydrangea-petiolaris.webp", caption: "Hydrangea petiolaris — newly identified" }] },
    ],
    "Red Hot Poker": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/red-hot-poker.webp", caption: "Red Hot Poker — not yet flowered" }] },
    ],
    "Forget-me-not": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/forget-me-not.webp", caption: "Forget-me-not — tiny blue flowers" }] },
    ],
    "Astilbe": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/astilbe-1.webp", caption: "Astilbe — flower spike emerging" },
        { src: "images/june-2026/astilbe-2.webp", caption: "Astilbe — foliage close-up" },
      ]},
    ],
    "Yucca": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/yucca.webp", caption: "Yucca — architectural form" }] },
    ],
    "Euonymus 'Emerald Gaiety'": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/euonymus-emerald-gaiety.webp", caption: "Newly moved from Bed 3 — white-margined leaves" }] },
    ],
    "Apple Tree": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/apple-tree.webp", caption: "Apple Tree" }] },
    ],
    "Avens": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/avens-1.webp", caption: "Avens" },
        { src: "images/june-2026/avens-2.webp", caption: "Close-up" },
        { src: "images/june-2026/avens-3.webp", caption: "Cluster" },
        { src: "images/june-2026/avens-4.webp", caption: "Wide" },
      ]},
    ],
    "Wisteria": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/wisteria.webp", caption: "Wisteria — June" }] },
    ],
    "Rose": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/rose.webp", caption: "Rose" }] },
    ],
    "Lavender": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/lavender.webp", caption: "Lavender — coming into flower" }] },
    ],
    "Houseleeks": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/houseleeks-1.webp", caption: "Houseleeks" },
        { src: "images/june-2026/houseleeks-2.webp", caption: "Rosette detail" },
      ]},
    ],
    "Stonecrop": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/stonecrop-1.webp", caption: "Stonecrop" },
        { src: "images/june-2026/stonecrop-2.webp", caption: "Mid-shot" },
        { src: "images/june-2026/stonecrop-3.webp", caption: "Close-up" },
      ]},
    ],
    "New Zealand Flax (dark)": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/phormium-dark.webp", caption: "Dark Phormium" }] },
    ],
    "Rosemary": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/rosemary.webp", caption: "Rosemary" }] },
    ],
    "Cabbage Tree": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/cordyline-1.webp", caption: "Cordyline" },
        { src: "images/june-2026/cordyline-2.webp", caption: "Mid-shot" },
        { src: "images/june-2026/cordyline-3.webp", caption: "Close-up" },
      ]},
    ],
    "Honeysuckle": [
      { month: "june-2026", label: "June 2026", photos: [
        { src: "images/june-2026/honeysuckle-1.webp", caption: "Honeysuckle" },
        { src: "images/june-2026/honeysuckle-2.webp", caption: "Flowers" },
      ]},
    ],
    "Clematis": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/clematis.webp", caption: "Clematis montana" }] },
    ],
    "Pear Tree": [
      { month: "june-2026", label: "June 2026", photos: [{ src: "images/june-2026/pear-tree.webp", caption: "Pear Tree — June" }] },
    ],
  };

  // ─── BED PLANT MAPS ───────────────────────────────────────────────
  // Each map is a list of {name, x, y, r, hue} for SVG circles.
  // Coordinates are in a 100×100 viewBox; the bed view scales it up.
  const BED_PLANT_MAPS = {
    bed1: [
      { name: "Japanese Maple", x: 50, y: 28, r: 22, hue: 18 },
      { name: "Japanese Aralia", x: 45, y: 50, r: 11, hue: 90 },
      { name: "Rhododendron", x: 22, y: 48, r: 10, hue: 60 },
      { name: "Astilbe", x: 78, y: 50, r: 9, hue: 350 },
      { name: "Dahlia", x: 50, y: 62, r: 9, hue: 0 },
      { name: "Hosta", x: 22, y: 75, r: 9, hue: 105 },
      { name: "Angel Wings", x: 50, y: 80, r: 8, hue: 70 },
      { name: "Box Hedging", x: 92, y: 50, r: 7, hue: 130 },
      { name: "Euonymus", x: 12, y: 88, r: 6, hue: 55 },
      { name: "Hardy Geranium", x: 82, y: 88, r: 6, hue: 280 },
      { name: "Nemesia", x: 65, y: 88, r: 5, hue: 25 },
      { name: "Wintercreeper", x: 78, y: 75, r: 7, hue: 55 },
    ],
    bed2: [
      { name: "Weeping Cherry", x: 22, y: 18, r: 14, hue: 340 },
      { name: "Variegated Dogwood", x: 22, y: 42, r: 11, hue: 0 },
      { name: "Hydrangea petiolaris", x: 52, y: 12, r: 10, hue: 210 },
      { name: "Weigela", x: 56, y: 56, r: 10, hue: 320 },
      { name: "Hosta", x: 40, y: 56, r: 8, hue: 105 },
      { name: "Silverbush", x: 76, y: 56, r: 8, hue: 70 },
      { name: "Peony", x: 22, y: 70, r: 12, hue: 350 },
      { name: "Centaurea 'Snowy Owl'", x: 88, y: 35, r: 7, hue: 200 },
      { name: "Red Hot Poker", x: 86, y: 68, r: 7, hue: 25 },
      { name: "Angel Wings", x: 30, y: 88, r: 7, hue: 70 },
      { name: "Forget-me-not", x: 46, y: 78, r: 5, hue: 220 },
      { name: "Maiden Pink", x: 62, y: 78, r: 5, hue: 330 },
      { name: "Kerria", x: 58, y: 88, r: 6, hue: 55 },
      { name: "Garden Pink", x: 72, y: 88, r: 5, hue: 340 },
      { name: "Euonymus 'Emerald Gaiety'", x: 86, y: 88, r: 6, hue: 110 },
    ],
    bed3: [
      { name: "Apple Tree", x: 50, y: 38, r: 22, hue: 105 },
      { name: "Avens", x: 50, y: 80, r: 11, hue: 25 },
    ],
    bed4: [
      { name: "Wisteria", x: 50, y: 16, r: 14, hue: 270 },
      { name: "Rose", x: 56, y: 50, r: 10, hue: 350 },
      { name: "Yucca", x: 24, y: 72, r: 9, hue: 90 },
      { name: "Lavender", x: 76, y: 76, r: 9, hue: 270 },
    ],
    stone: [
      { name: "Houseleeks", x: 22, y: 50, r: 7, hue: 130 },
      { name: "Stonecrop", x: 36, y: 50, r: 7, hue: 90 },
      { name: "New Zealand Flax (dark)", x: 50, y: 50, r: 9, hue: 0 },
      { name: "Rosemary", x: 64, y: 50, r: 7, hue: 200 },
      { name: "Cabbage Tree", x: 80, y: 50, r: 11, hue: 350 },
      { name: "Hebe", x: 14, y: 72, r: 6, hue: 260 },
    ],
    patio: [
      { name: "Clematis", x: 18, y: 50, r: 14, hue: 320 },
      { name: "Honeysuckle", x: 82, y: 50, r: 10, hue: 50 },
    ],
    pear: [
      { name: "Pear Tree", x: 50, y: 50, r: 30, hue: 100 },
    ],
    bigpot1: [
      { name: "Fuchsia", x: 50, y: 25, r: 14, hue: 340 },
      { name: "Verbena", x: 22, y: 55, r: 10, hue: 330 },
      { name: "Calibrachoa", x: 50, y: 65, r: 10, hue: 350 },
      { name: "Nepeta", x: 78, y: 40, r: 9, hue: 250 },
      { name: "Lobelia", x: 20, y: 80, r: 8, hue: 230 },
      { name: "Petunia", x: 75, y: 72, r: 9, hue: 280 },
    ],
    bigpot2: [
      { name: "Lobelia", x: 20, y: 35, r: 10, hue: 230 },
      { name: "Verbena", x: 55, y: 30, r: 10, hue: 330 },
      { name: "Petunia", x: 78, y: 50, r: 10, hue: 280 },
      { name: "Nepeta", x: 50, y: 55, r: 9, hue: 250 },
      { name: "Fuchsia", x: 50, y: 25, r: 12, hue: 340 },
    ],
    littlepot1: [
      { name: "Geranium", x: 45, y: 32, r: 18, hue: 0 },
      { name: "Petunia", x: 50, y: 72, r: 16, hue: 230 },
    ],
    littlepot2: [
      { name: "Geranium", x: 45, y: 32, r: 18, hue: 0 },
      { name: "Petunia", x: 50, y: 72, r: 16, hue: 280 },
    ],
    baskets: [
      { name: "Trailing Fuchsia", x: 22, y: 50, r: 16, hue: 340 },
      { name: "Bacopa", x: 52, y: 25, r: 12, hue: 200 },
      { name: "Trailing Lobelia", x: 78, y: 50, r: 12, hue: 230 },
      { name: "Trailing Verbena", x: 50, y: 75, r: 12, hue: 330 },
    ],
  };

  // ─── PALETTES ─────────────────────────────────────────────────────
  // All palettes use the same paper-and-ink semantics so the rest of
  // the app just reads CSS vars.
  const PALETTES = {
    spring: {
      label: "Spring · cream paper",
      paper: "#f3ecda",
      paperDeep: "#e8dec5",
      ink: "#2b271c",
      pencil: "#7a6e54",
      stamp: "#a23a2c",
      green: "#4f6d35",
      accent: "#9c5a2c",
      tape: "#e7d9b8",
    },
    summer: {
      label: "Summer · sun-faded",
      paper: "#f6efd9",
      paperDeep: "#ead9b0",
      ink: "#3a2f1d",
      pencil: "#8c7a4f",
      stamp: "#c0762a",
      green: "#6a8a3a",
      accent: "#bb6a2c",
      tape: "#ecd99b",
    },
    autumn: {
      label: "Autumn · oxidized",
      paper: "#ece1c9",
      paperDeep: "#d9c8a3",
      ink: "#2d2014",
      pencil: "#7a5a3a",
      stamp: "#8a3a18",
      green: "#5a5a25",
      accent: "#a8501f",
      tape: "#d6b876",
    },
    winter: {
      label: "Winter · cool linen",
      paper: "#ecebe3",
      paperDeep: "#d8d6c9",
      ink: "#1f2024",
      pencil: "#5d6166",
      stamp: "#5a6a85",
      green: "#3f5a45",
      accent: "#6a7e8c",
      tape: "#cfd3c4",
    },
    night: {
      label: "Night · graphite",
      paper: "#1c2018",
      paperDeep: "#141911",
      ink: "#e7e0cb",
      pencil: "#a59a7e",
      stamp: "#cf7a4a",
      green: "#a3c06a",
      accent: "#d6a168",
      tape: "#3a4030",
    },
  };

  return { ZONES, PLANTS, PHOTOS_BY_MONTH, PLANT_PHOTOS, BED_PLANT_MAPS, PALETTES };
})();
