// Oak Lodge Garden — data module
// Zones, plants (per the brief), photo paths (May 2026), and bed plant maps.

window.OAK = (function () {
  // ─── ZONES ────────────────────────────────────────────────────────
  // SVG coords from the brief (viewBox 820x620, ~50px = 1m)
  const ZONES = {
    bed1: {
      id: "bed1",
      title: "Flower Bed 1",
      badge: "Raised timber bed",
      dims: "2.6m × 2.6m",
      where: "Corner by the gate, upper level",
      desc:
        "Raised timber-edged bed dominated by a Japanese Maple. Layered shade-tolerant planting underneath — Fatsia, Hosta, Astilbe — with a clipped box edge.",
      shape: { kind: "rect", x: 75, y: 38, w: 130, h: 130 },
      color: "#8b5e3c",
      labelXY: [140, 105],
      plantKey: "Bed 1",
    },
    bed2: {
      id: "bed2",
      title: "Flower Bed 2",
      badge: "Long border",
      dims: "T-shape, between walls",
      where: "Lower level, west boundary",
      desc:
        "T-shaped border running between two brick walls. Weeping cherry overhangs the back, with peony, dogwood and weigela through the body. Maiden pink and nemesia spill from the wall gap.",
      shape: {
        kind: "polygon",
        points: "30,250 130,250 130,335 300,335 300,395 130,395 130,475 30,475",
      },
      color: "#6b8e4e",
      labelXY: [80, 290],
      plantKey: "Bed 2",
    },
    bed3: {
      id: "bed3",
      title: "Flower Bed 3",
      badge: "Compact bed",
      dims: "0.8m × 0.8m",
      where: "Junction of steps and stone bed",
      desc:
        "Tiny pocket bed at the foot of the steps. An apple tree with bird feeders, hemmed in by avens and wintercreeper.",
      shape: { kind: "rect", x: 490, y: 267, w: 40, h: 40 },
      color: "#c7a54a",
      labelXY: [510, 257],
      plantKey: "Bed 3",
    },
    bed4: {
      id: "bed4",
      title: "Flower Bed 4",
      badge: "Boundary bed",
      dims: "2m × 3.8m, mirrored L",
      where: "Right boundary wall, upper",
      desc:
        "Mirrored-L bed against the right boundary. Wisteria cascading from the wall, with phormium, yucca and lavender giving year-round structure. A climbing rose on the trellis.",
      shape: {
        kind: "polygon",
        points: "715,55 765,55 765,255 585,255 585,205 715,205",
      },
      color: "#8e6fbf",
      labelXY: [665, 140],
      plantKey: "Bed 4",
    },
    stone: {
      id: "stone",
      title: "Stone Bed",
      badge: "Gravel bed",
      dims: "≈4.8m × 1m",
      where: "Decking edge, lower level",
      desc:
        "Narrow gravel bed running along the decking edge. Mediterranean planting — houseleeks, sedum, rosemary — anchored by a Cordyline and a dark Phormium.",
      shape: { kind: "rect", x: 530, y: 267, w: 225, h: 48 },
      color: "#7a8f9a",
      labelXY: [640, 290],
      plantKey: "Stone Bed",
    },
    steps: {
      id: "steps",
      title: "Steps",
      badge: "Hardscape",
      dims: "≈3m × 3m",
      where: "Connecting upper and lower",
      desc: "Block paving with brick edging, several levels stepping down.",
      shape: { kind: "rect", x: 300, y: 260, w: 185, h: 150 },
      color: "#6e6e5e",
      labelXY: [392, 335],
    },
    patio: {
      id: "patio",
      title: "Decking",
      badge: "Composite deck",
      dims: "≈6m × 3m",
      where: "Lower level, by the house",
      desc:
        "Composite decking running along the back of the house. A mature Clematis montana climbs the left house wall.",
      shape: { kind: "rect", x: 488, y: 318, w: 277, h: 155 },
      color: "#8a7e6b",
      labelXY: [625, 395],
      plantKey: "Patio",
    },
    kitchen: {
      id: "kitchen",
      title: "Patio Kitchen",
      badge: "Outdoor room",
      dims: "1.6m × 1.4m",
      where: "Sheltered between brick walls",
      desc: "Sheltered outdoor kitchen tucked between the walls.",
      shape: { kind: "rect", x: 175, y: 400, w: 105, h: 70 },
      color: "#5c6b54",
      labelXY: [228, 435],
    },
    lounge: {
      id: "lounge",
      title: "Patio Lounge",
      badge: "Seating",
      dims: "≈3m × 1.4m",
      where: "Lower terrace, between kitchen and patio",
      desc: "Lower seating area linking kitchen to patio.",
      shape: { kind: "rect", x: 283, y: 413, w: 200, h: 60 },
      color: "#5c6b54",
      labelXY: [383, 443],
    },
    pear: {
      id: "pear",
      title: "Pear Tree",
      badge: "Specimen tree",
      dims: "Mature canopy",
      where: "Upper terrace, near gate",
      desc: "A mature pear tree on the upper terrace, near the gate.",
      shape: { kind: "rect", x: 448, y: 33, w: 64, h: 64 },
      color: "#3a6830",
      labelXY: [480, 70],
      plantKey: "Tree",
    },
  };

  // ─── PLANTS ───────────────────────────────────────────────────────
  // Care info synthesized from horticultural common knowledge per the brief.
  const PLANTS = {
    "Bed 1": [
      {
        name: "Japanese Maple",
        latin: "Acer palmatum",
        photos: ["images/plants/japanese-maple.webp", "images/plants/japanese-maple-1.webp"],
        position: "Back centre — dominant canopy",
        light: "Dappled shade to partial sun. Sheltered from harsh afternoon sun.",
        water: "Keep soil consistently moist but never waterlogged.",
        care: "Slightly acidic, well-drained loam. Mulch in spring; minimal pruning.",
        seasonal: "New leaves emerge red-bronze in April; fiery red autumn colour; bare and architectural in winter.",
      },
      {
        name: "Japanese Aralia",
        latin: "Fatsia japonica 'Spider's Web'",
        photos: ["images/plants/japanese-aralia.webp", "images/plants/japanese-aralia-2.webp", "images/plants/japanese-aralia-3.webp"],
        position: "Mid-centre, under the Acer",
        light: "Shade to partial shade. Tolerates deep shade.",
        water: "Moderate; let top inch dry between waterings.",
        care: "Rich, well-drained soil. Cut back leggy stems in spring.",
        seasonal: "Evergreen with cream-flecked leaves; cream globe flowers October–November.",
      },
      {
        name: "Rhododendron",
        latin: "Rhododendron 'Goldflimmer'",
        photos: ["images/plants/rhododendron.webp", "images/plants/rhododendron-2.webp"],
        position: "Mid-left, variegated evergreen",
        light: "Partial shade. Avoid hot, dry sun.",
        water: "Even moisture; never waterlogged.",
        care: "Acidic, ericaceous soil. Mulch with leaf mould; deadhead spent flowers.",
        seasonal: "Evergreen golden-variegated leaves year-round; lavender-purple flowers May.",
      },
      {
        name: "Astilbe",
        latin: "Astilbe",
        photos: ["images/plants/astilbe.webp"],
        position: "Right side — feathery plumes in summer",
        light: "Partial shade; tolerates more sun if soil stays moist.",
        water: "Loves moisture. Water freely in dry spells.",
        care: "Humus-rich soil. Cut back to ground in late winter.",
        seasonal: "Pink feathery plumes June–August; ferny foliage spring–autumn.",
      },
      {
        name: "Hosta",
        latin: "Hosta",
        photos: ["images/plants/hosta-gold-standard.webp", "images/plants/hosta-patriot.webp", "images/plants/hosta-patriot-2.webp", "images/plants/hosta-francee.webp"],
        position: "Front-left, green/white variegation",
        light: "Shade to partial shade.",
        water: "Keep soil moist; mulch to retain moisture.",
        care: "Watch for slugs and snails. Divide clumps every few years.",
        seasonal: "Foliage emerges April; lilac flowers July; dies back in autumn.",
      },
      {
        name: "Angel Wings",
        latin: "Senecio candicans",
        photos: ["images/plants/angel-wings-1.webp", "images/plants/angel-wings-2.webp", "images/plants/angel-wings-3.webp"],
        position: "Front-centre — silvery-white leaves",
        light: "Full sun to partial sun.",
        water: "Drought-tolerant once established. Avoid overwatering.",
        care: "Free-draining soil. Tender — protect or lift in hard winters.",
        seasonal: "Silver-white furry leaves all season; small yellow flowers if happy.",
      },
      {
        name: "Box Hedging",
        latin: "Buxus sempervirens",
        photos: [],
        position: "Full right edge — clipped",
        light: "Sun or partial shade.",
        water: "Moderate; established plants tolerate dry spells.",
        care: "Clip twice yearly (May and August). Watch for box blight.",
        seasonal: "Evergreen year-round.",
      },
      {
        name: "Euonymus",
        latin: "Euonymus fortunei (golden)",
        photos: [],
        position: "Front-left corner",
        light: "Sun or partial shade.",
        water: "Moderate; very tolerant once established.",
        care: "Trim to shape in spring. Tough and trouble-free.",
        seasonal: "Golden-variegated evergreen; pink tints in cold weather.",
      },
      {
        name: "Hardy Geranium",
        latin: "Geranium spp.",
        photos: ["images/plants/hardy-geranium.webp"],
        position: "Front-right — spreading low clumps",
        light: "Sun to partial shade. Very adaptable.",
        water: "Low to moderate once established.",
        care: "Cut back hard after first flush for a second showing. Divide every 3–4 years.",
        seasonal: "Deeply lobed foliage from April; purple-blue flowers May–July, often a second flush in autumn.",
      },
      {
        name: "English Daisy",
        latin: "Bellis perennis",
        photos: [],
        position: "Front-centre — pink pom-poms",
        light: "Sun to partial shade.",
        water: "Moderate.",
        care: "Deadhead to prolong flowering; biennial — may self-seed.",
        seasonal: "Pink double flowers April–July.",
      },
    ],
    "Bed 2": [
      {
        name: "Weeping Cherry",
        latin: "Prunus species",
        photos: ["images/plants/weeping-cherry.webp", "images/plants/weeping-cherry-1.webp", "images/plants/weeping-cherry-2.webp"],
        position: "Upper section — overhanging the wall",
        light: "Full sun.",
        water: "Moderate; deep watering when young.",
        care: "Light pruning after flowering; avoid heavy cuts.",
        seasonal: "Pink blossom April; green canopy summer; bare winter.",
      },
      {
        name: "Variegated Dogwood",
        latin: "Cornus alba 'Elegantissima'",
        photos: ["images/plants/variegated-dogwood.webp"],
        position: "Upper section — red winter stems",
        light: "Sun or partial shade.",
        water: "Moisture-loving; tolerates wet soil.",
        care: "Cut a third of stems to ground each March for best winter colour.",
        seasonal: "Cream-edged leaves spring–autumn; brilliant red stems winter.",
      },
      {
        name: "Peony",
        latin: "Paeonia lactiflora",
        photos: ["images/plants/peony.webp"],
        position: "Lower section",
        light: "Full sun, sheltered.",
        water: "Moderate; deep watering when budding.",
        care: "Don't bury the crown. Stake floppy heads. Resents being moved.",
        seasonal: "Huge fragrant flowers May–June; foliage to ground in autumn.",
      },
      {
        name: "Weigela",
        latin: "Weigela florida",
        photos: ["images/plants/weigela.webp"],
        position: "Mid section",
        light: "Full sun.",
        water: "Moderate.",
        care: "Prune one in three old stems after flowering.",
        seasonal: "Pink trumpet flowers May–June; sometimes a second flush.",
      },
      {
        name: "Silverbush",
        latin: "Convolvulus cneorum",
        photos: ["images/plants/silverbush.webp", "images/plants/silverbush-2.webp", "images/plants/silverbush-3.webp"],
        position: "Mid-right — silvery foliage",
        light: "Full sun.",
        water: "Drought-tolerant. Hates wet feet.",
        care: "Sharp drainage essential. Light trim after flowering.",
        seasonal: "White trumpet flowers May–September on silver mound.",
      },
      {
        name: "Hosta",
        latin: "Hosta",
        position: "Lower, front-left",
        light: "Shade to partial shade.",
        water: "Keep moist.",
        care: "Slug protection; divide every few years.",
        seasonal: "Emerges April; lilac flowers July.",
      },
      {
        name: "Angel Wings",
        latin: "Senecio candicans",
        position: "Lower, front",
        light: "Full sun.",
        water: "Drought-tolerant.",
        care: "Free-draining soil; tender in hard winters.",
        seasonal: "Silver foliage all season.",
      },
      {
        name: "Kerria",
        latin: "Kerria japonica",
        photos: ["images/plants/kerria.webp", "images/plants/kerria-1.webp"],
        position: "Against the wall — arching stems with yellow flowers",
        light: "Partial shade to full sun.",
        water: "Low to moderate. Tolerates dry shade.",
        care: "Cut flowered stems back to the base after flowering. Remove all-green suckers promptly.",
        seasonal: "Bright single yellow flowers April–May; arching green stems attractive all year.",
      },
      {
        name: "Forget-me-not",
        latin: "Myosotis",
        photos: ["images/plants/forget-me-not.webp"],
        position: "Lower — small blue flowers",
        light: "Sun to partial shade.",
        water: "Moderate.",
        care: "Biennial; lets itself seed about. Pull spent plants in summer.",
        seasonal: "Sky-blue clouds April–June.",
      },
      {
        name: "Maiden Pink",
        latin: "Dianthus deltoides",
        photos: ["images/plants/maiden-pink.webp"],
        position: "Between walls — pink flowers",
        light: "Full sun.",
        water: "Low; sharp drainage.",
        care: "Trim after flowering. Mat-forming.",
        seasonal: "Pink stars June–August.",
      },
      {
        name: "Garden Pink",
        latin: "Dianthus plumarius",
        photos: ["images/plants/dianthus.webp", "images/plants/dianthus-1.webp", "images/plants/dianthus-2.webp"],
        position: "Lower front — compact fragrant mound",
        light: "Full sun.",
        water: "Low. Sharp drainage essential.",
        care: "Deadhead to extend flowering. Cut back after main flush. Replace plants every 3 years as they become woody.",
        seasonal: "Fragrant double pink flowers June–August; silver-grey cushion foliage year-round.",
      },
      {
        name: "Nemesia",
        latin: "Nemesia spp.",
        photos: ["images/plants/nemesia.webp", "images/plants/nemesia-1.webp", "images/plants/nemesia-2.webp"],
        position: "Between walls — orange/coral",
        light: "Full sun.",
        water: "Moderate; don't let pots dry out.",
        care: "Deadhead and trim back to keep flowering.",
        seasonal: "Continuous flowers May–October.",
      },
    ],
    "Bed 3": [
      {
        name: "Apple Tree",
        latin: "Malus domestica",
        photos: ["images/plants/apple-tree.webp", "images/plants/apple-tree-1.webp"],
        position: "Centre — with bird feeders",
        light: "Full sun.",
        water: "Deep watering in dry spells, especially when fruiting.",
        care: "Winter prune for shape. Thin fruit in June for size.",
        seasonal: "Blossom April; fruit August–October; bare winter.",
      },
      {
        name: "Avens",
        latin: "Geum",
        photos: ["images/plants/avens-orange.webp", "images/plants/avens-red-orange.webp", "images/plants/avens-orange-2.webp", "images/plants/avens-orange-3.webp"],
        position: "Front-left — orange flowers",
        light: "Sun or partial shade.",
        water: "Moderate.",
        care: "Deadhead. Divide every few years.",
        seasonal: "Orange flowers May–July, often a second flush.",
      },
      {
        name: "Wintercreeper",
        latin: "Euonymus fortunei",
        photos: ["images/plants/wintercreeper.webp", "images/plants/wintercreeper-silver-queen.webp", "images/plants/wintercreeper-3.webp"],
        position: "Front-right — variegated evergreen",
        light: "Sun or partial shade.",
        water: "Moderate.",
        care: "Trim to shape in spring.",
        seasonal: "Evergreen; pink tints in cold.",
      },
    ],
    "Bed 4": [
      {
        name: "Wisteria",
        latin: "Wisteria spp.",
        photos: ["images/plants/wisteria.webp", "images/plants/wisteria-1.webp", "images/plants/wisteria-2.webp"],
        position: "Top — cascading over the wall",
        light: "Full sun.",
        water: "Deep watering when young; established plants tolerate drought.",
        care: "Prune twice yearly: August (long shoots to 6 leaves) and February (back to 2–3 buds).",
        seasonal: "Lilac racemes May; bare gnarled stems winter.",
      },
      {
        name: "New Zealand Flax",
        latin: "Phormium",
        photos: ["images/plants/phormium-yellow.webp"],
        position: "Upper-mid — sword-shaped leaves",
        light: "Full sun.",
        water: "Moderate; drought-tolerant established.",
        care: "Remove old leaves at the base. Tough, almost no maintenance.",
        seasonal: "Evergreen architectural foliage year-round.",
      },
      {
        name: "Rose",
        latin: "Rosa",
        photos: ["images/plants/rose.webp"],
        position: "Mid — on trellis/support",
        light: "Full sun.",
        water: "Deep watering, mulch in spring.",
        care: "Prune in late winter. Feed in spring and after first flush.",
        seasonal: "Flowers June–September; bare winter.",
      },
      {
        name: "Yucca",
        latin: "Yucca filamentosa",
        photos: ["images/plants/yucca.webp", "images/plants/yucca-1.webp"],
        position: "Lower-left — spiky, architectural",
        light: "Full sun.",
        water: "Drought-tolerant.",
        care: "Free-draining soil. Almost indestructible.",
        seasonal: "Evergreen; spire of white bell flowers in summer when mature.",
      },
      {
        name: "Lavender",
        latin: "Lavandula angustifolia",
        photos: [],
        position: "Right — grey-green foliage",
        light: "Full sun.",
        water: "Drought-tolerant.",
        care: "Trim lightly after flowering and again in spring. Don't cut into old wood.",
        seasonal: "Purple flower spikes June–August; aromatic year-round.",
      },
    ],
    "Stone Bed": [
      {
        name: "Aubrieta",
        latin: "Aubrieta deltoidea",
        photos: ["images/plants/aubrieta.webp"],
        position: "Left end — purple spring flowers",
        light: "Full sun.",
        water: "Low.",
        care: "Trim hard after flowering.",
        seasonal: "Sheets of purple April–May.",
      },
      {
        name: "Houseleeks",
        latin: "Sempervivum",
        photos: ["images/plants/houseleek.webp"],
        position: "Left-centre — rosettes in gravel",
        light: "Full sun.",
        water: "Very low. Hates wet.",
        care: "Sharp drainage; almost no maintenance.",
        seasonal: "Evergreen rosettes; flowering rosettes die after blooming, replaced by offsets.",
      },
      {
        name: "Stonecrop",
        latin: "Sedum (trailing)",
        photos: ["images/plants/stonecrop-1.webp", "images/plants/stonecrop-2.webp", "images/plants/stonecrop-3.webp"],
        position: "Centre-left",
        light: "Full sun.",
        water: "Low.",
        care: "Free-draining soil. Cut back in late winter.",
        seasonal: "Foliage year-round; flowers summer–autumn.",
      },
      {
        name: "New Zealand Flax (dark)",
        latin: "Phormium 'Platt's Black'",
        photos: ["images/plants/phormium.webp", "images/plants/phormium-1.webp"],
        position: "Centre — dark burgundy spikes",
        light: "Full sun.",
        water: "Moderate; drought-tolerant once established.",
        care: "Remove old leaves at base. Architectural and low-care.",
        seasonal: "Evergreen dark foliage year-round.",
      },
      {
        name: "Rosemary",
        latin: "Salvia rosmarinus",
        photos: ["images/plants/rosemary.webp"],
        position: "Centre-right — grey-green needles",
        light: "Full sun.",
        water: "Low.",
        care: "Sharp drainage. Light trim after flowering.",
        seasonal: "Evergreen aromatic; pale blue flowers spring.",
      },
      {
        name: "Cabbage Tree",
        latin: "Cordyline australis 'Red Star'",
        photos: ["images/plants/cordyline.webp"],
        position: "Right — large palm-like tree",
        light: "Full sun.",
        water: "Moderate; established plants tolerate drought.",
        care: "Tie up leaves in winter to protect crown if hard frost forecast.",
        seasonal: "Evergreen burgundy fountain of leaves.",
      },
      {
        name: "Hebe",
        latin: "Hebe (syn. Veronica) cultivar",
        photos: ["images/plants/hebe.webp"],
        position: "Stone Bed — variegated foliage shrub",
        light: "Full sun to partial shade.",
        water: "Moderate. Good drainage. Dislikes waterlogging.",
        care: "Light trim after flowering. Not fully hardy — protect in prolonged hard frosts. Note: botanically reclassified from Hebe to Veronica, though widely sold under both names. Visual traits suggest \'Heartbreaker\' or a closely related variegated cultivar.",
        seasonal: "Evergreen variegated foliage year-round; small purple-white flower spikes in summer.",
      },
      {
        name: "Honeysuckle",
        latin: "Lonicera",
        photos: [],
        position: "Far right",
        light: "Sun, with shaded roots.",
        water: "Moderate.",
        care: "Light prune after flowering. Train onto support.",
        seasonal: "Fragrant flowers June–August.",
      },
    ],
    Patio: [
      {
        name: "Clematis",
        latin: "Clematis montana",
        photos: ["images/plants/clematis.webp"],
        position: "Left side of house wall — mature woody stems",
        light: "Sun, with shaded roots.",
        water: "Moderate.",
        care: "Group 1 clematis — light prune after flowering only. Tie in new growth.",
        seasonal: "Sheets of pale pink flowers May; vigorous summer growth.",
      },
    ],
    Tree: [
      {
        name: "Pear Tree",
        latin: "Pyrus",
        photos: ["images/plants/pear-tree.webp", "images/plants/pear-tree-1.webp", "images/plants/pear-tree-2.webp"],
        position: "Upper terrace — near the gate",
        light: "Full sun.",
        water: "Deep watering in dry summers.",
        care: "Winter prune for shape. Thin fruit if heavy.",
        seasonal: "White blossom April; fruit September; bare winter.",
      },
    ],
  };

  // ─── PHOTOS (May 2026) ────────────────────────────────────────────
  const PHOTOS_BY_MONTH = {
    "may-2026": {
      label: "May 2026",
      bed1: [
        { src: "images/may-2026/bed1.jpg",        caption: "Overview from paving" },
        { src: "images/may-2026/bed1-close1.jpg",  caption: "Japanese Maple area" },
        { src: "images/may-2026/bed1-close2.jpg",  caption: "Front planting" },
        { src: "images/may-2026/bed1-3.webp",      caption: "From above" },
        { src: "images/may-2026/bed1-4.webp",      caption: "From upper terrace" },
        { src: "images/may-2026/bed1-wide.webp",   caption: "Wide shot from street" },
        { src: "images/may-2026/bed1-wide-2.webp", caption: "From gate, angle 2" },
        { src: "images/may-2026/bed1-maple.webp",  caption: "Japanese Maple from street" },
        { src: "images/may-2026/bed1-close3.webp", caption: "Box edging detail" },
        { src: "images/may-2026/bed1-7.webp",      caption: "Box hedging close" },
      ],
      bed2: [
        { src: "images/may-2026/bed2-1.jpg",       caption: "Overview, angle 1" },
        { src: "images/may-2026/bed2-2.jpg",       caption: "Overview, angle 2" },
        { src: "images/may-2026/bed2-kitchen.jpg", caption: "From the patio kitchen" },
        { src: "images/may-2026/bed2-steps.jpg",   caption: "From the steps" },
        { src: "images/may-2026/bed2-south1.jpg",  caption: "South angle 1" },
        { src: "images/may-2026/bed2-south2.jpg",  caption: "South angle 2" },
        { src: "images/may-2026/bed2-wide.webp",   caption: "Wide overview" },
        { src: "images/may-2026/bed2-3.webp",      caption: "From lower paving" },
        { src: "images/may-2026/bed2-4.webp",      caption: "Steps side" },
        { src: "images/may-2026/bed2-5.webp",      caption: "Lower angle" },
        { src: "images/may-2026/bed2-6.webp",      caption: "From patio" },
      ],
      bed3: [
        { src: "images/may-2026/bed3.jpg",         caption: "Apple tree & avens" },
        { src: "images/may-2026/bed3-detail.jpg",  caption: "From lower paving" },
        { src: "images/may-2026/bed3-3.webp",      caption: "Apple tree & bird feeders" },
      ],
      bed4: [
        { src: "images/may-2026/bed4.jpg",         caption: "Wisteria overview" },
        { src: "images/may-2026/bed4-wide.jpg",    caption: "Wider angle" },
        { src: "images/may-2026/bed4-3.webp",      caption: "Wisteria in full flower" },
      ],
      stone: [
        { src: "images/may-2026/stone-bed.jpg",         caption: "Overview" },
        { src: "images/may-2026/stone-bed-wide.jpg",    caption: "From the patio" },
        { src: "images/may-2026/stone-bed-detail1.jpg", caption: "Phormium & houseleeks" },
        { src: "images/may-2026/stone-bed-detail2.jpg", caption: "Cordyline Red Star" },
        { src: "images/may-2026/stone-bed-5.webp",      caption: "Stone bed & decking" },
        { src: "images/may-2026/stone-bed-6.webp",      caption: "From above" },
        { src: "images/may-2026/stone-bed-wide-2.webp", caption: "Wide, from patio" },
        { src: "images/may-2026/stone-bed-7.webp",      caption: "With Cordyline" },
      ],
      patio: [
        { src: "images/may-2026/patio.jpg",            caption: "Decking" },
        { src: "images/may-2026/patio-door.jpg",       caption: "Towards the house" },
        { src: "images/may-2026/patio-clematis.jpg",   caption: "Clematis montana" },
        { src: "images/may-2026/patio-clematis-2.webp",caption: "Clematis in full bloom" },
        { src: "images/may-2026/patio-2.webp",         caption: "Circular paving" },
        { src: "images/may-2026/patio-3.webp",         caption: "Decking full length" },
      ],
      steps: [
        { src: "images/may-2026/steps.jpg",        caption: "Steps between levels" },
        { src: "images/may-2026/steps-2.webp",     caption: "Steps from front" },
        { src: "images/may-2026/steps-wide.webp",  caption: "Wide view from above" },
        { src: "images/may-2026/steps-3.webp",     caption: "Upper terrace looking down" },
      ],
      kitchen: [],
      lounge: [
        { src: "images/may-2026/lounge.webp", caption: "Side passage" },
      ],
      pear: [
        { src: "images/may-2026/pear.webp",   caption: "Pear tree area" },
        { src: "images/may-2026/pear-2.webp", caption: "Upper garden overview" },
      ],
    },
  };

  // ─── BED PLANT MAPS ───────────────────────────────────────────────
  // Each map is a list of {name, x, y, r, hue} for SVG circles.
  // Coordinates are in a 100×100 viewBox; the bed view scales it up.
  const BED_PLANT_MAPS = {
    bed1: [
      { name: "Japanese Maple", x: 50, y: 28, r: 22, hue: 18 },
      { name: "Japanese Aralia", x: 45, y: 50, r: 11, hue: 90 },
      { name: "Rhododendron", x: 22, y: 48, r: 10, hue: 60 },
      { name: "Astilbe", x: 78, y: 50, r: 9, hue: 350 },
      { name: "Hosta", x: 22, y: 75, r: 9, hue: 105 },
      { name: "Angel Wings", x: 50, y: 80, r: 8, hue: 70 },
      { name: "Box Hedging", x: 92, y: 50, r: 7, hue: 130 },
      { name: "Euonymus", x: 12, y: 88, r: 6, hue: 55 },
      { name: "English Daisy", x: 60, y: 90, r: 5, hue: 340 },
      { name: "Hardy Geranium", x: 82, y: 88, r: 6, hue: 280 },
    ],
    bed2: [
      { name: "Weeping Cherry", x: 22, y: 18, r: 14, hue: 340 },
      { name: "Variegated Dogwood", x: 22, y: 42, r: 11, hue: 0 },
      { name: "Weigela", x: 56, y: 56, r: 10, hue: 320 },
      { name: "Silverbush", x: 76, y: 56, r: 8, hue: 70 },
      { name: "Peony", x: 22, y: 70, r: 12, hue: 350 },
      { name: "Hosta", x: 14, y: 88, r: 7, hue: 105 },
      { name: "Angel Wings", x: 30, y: 88, r: 7, hue: 70 },
      { name: "Forget-me-not", x: 46, y: 78, r: 5, hue: 220 },
      { name: "Maiden Pink", x: 70, y: 78, r: 5, hue: 330 },
      { name: "Nemesia", x: 86, y: 78, r: 5, hue: 25 },
      { name: "Kerria", x: 58, y: 88, r: 6, hue: 55 },
      { name: "Garden Pink", x: 72, y: 88, r: 5, hue: 340 },
    ],
    bed3: [
      { name: "Apple Tree", x: 50, y: 38, r: 22, hue: 105 },
      { name: "Avens", x: 26, y: 78, r: 9, hue: 25 },
      { name: "Wintercreeper", x: 74, y: 78, r: 9, hue: 55 },
    ],
    bed4: [
      { name: "Wisteria", x: 50, y: 16, r: 14, hue: 270 },
      { name: "New Zealand Flax", x: 28, y: 42, r: 10, hue: 130 },
      { name: "Rose", x: 56, y: 50, r: 10, hue: 350 },
      { name: "Yucca", x: 24, y: 72, r: 9, hue: 90 },
      { name: "Lavender", x: 76, y: 76, r: 9, hue: 270 },
    ],
    stone: [
      { name: "Aubrieta", x: 8, y: 50, r: 7, hue: 280 },
      { name: "Houseleeks", x: 22, y: 50, r: 7, hue: 130 },
      { name: "Stonecrop", x: 36, y: 50, r: 7, hue: 90 },
      { name: "New Zealand Flax (dark)", x: 50, y: 50, r: 9, hue: 0 },
      { name: "Rosemary", x: 64, y: 50, r: 7, hue: 200 },
      { name: "Cabbage Tree", x: 80, y: 50, r: 11, hue: 350 },
      { name: "Honeysuckle", x: 94, y: 50, r: 7, hue: 50 },
      { name: "Hebe", x: 14, y: 72, r: 6, hue: 260 },
    ],
    patio: [
      { name: "Clematis", x: 18, y: 50, r: 14, hue: 320 },
    ],
    pear: [
      { name: "Pear Tree", x: 50, y: 50, r: 30, hue: 100 },
    ],
  };

  // ─── PALETTES ─────────────────────────────────────────────────────
  // All palettes use the same paper-and-ink semantics so the rest of
  // the app just reads CSS vars.
  const PALETTES = {
    spring: {
      label: "Spring · cream paper",
      paper: "#f3ecda",
      paperDeep: "#e8dec5",
      ink: "#2b271c",
      pencil: "#7a6e54",
      stamp: "#a23a2c",
      green: "#4f6d35",
      accent: "#9c5a2c",
      tape: "#e7d9b8",
    },
    summer: {
      label: "Summer · sun-faded",
      paper: "#f6efd9",
      paperDeep: "#ead9b0",
      ink: "#3a2f1d",
      pencil: "#8c7a4f",
      stamp: "#c0762a",
      green: "#6a8a3a",
      accent: "#bb6a2c",
      tape: "#ecd99b",
    },
    autumn: {
      label: "Autumn · oxidized",
      paper: "#ece1c9",
      paperDeep: "#d9c8a3",
      ink: "#2d2014",
      pencil: "#7a5a3a",
      stamp: "#8a3a18",
      green: "#5a5a25",
      accent: "#a8501f",
      tape: "#d6b876",
    },
    winter: {
      label: "Winter · cool linen",
      paper: "#ecebe3",
      paperDeep: "#d8d6c9",
      ink: "#1f2024",
      pencil: "#5d6166",
      stamp: "#5a6a85",
      green: "#3f5a45",
      accent: "#6a7e8c",
      tape: "#cfd3c4",
    },
    night: {
      label: "Night · graphite",
      paper: "#1c2018",
      paperDeep: "#141911",
      ink: "#e7e0cb",
      pencil: "#a59a7e",
      stamp: "#cf7a4a",
      green: "#a3c06a",
      accent: "#d6a168",
      tape: "#3a4030",
    },
  };

  return { ZONES, PLANTS, PHOTOS_BY_MONTH, BED_PLANT_MAPS, PALETTES };
})();
