// Oak Lodge Garden — visual change journal
// Explicit history only: do not derive events from the current plant inventory.

(() => {
  const OAK = window.OAK = window.OAK || {};

  OAK.JOURNAL = {
    version: 1,
    entries: [
      {
        id: "jul-2026",
        year: 2026,
        month: 7,
        label: "July 2026",
        title: "The garden changed shape",
        note: "A big month at Oak Lodge. The Stone Bed became a proper alpine and succulent garden, plants found better homes across the back and front, and I finally recorded the house palm too.",
        photos: [
          {
            id: "jul-2026-stone-before",
            area: "back",
            src: "images/jul-2026/stone-bed-before-lavender-removal-1.webp",
            caption: "Stone Bed before the late-July replant",
            badge: "before",
            pair: "stone-july",
          },
          {
            id: "jul-2026-stone-after",
            area: "back",
            src: "images/jul-2026/stone-bed-after-replanting-1.webp",
            caption: "The new alpine and succulent planting",
            badge: "after",
            pair: "stone-july",
          },
          {
            id: "jul-2026-front-bed2",
            area: "front",
            src: "images/jul-2026/front-bed2-after-bark-1.webp",
            caption: "Front Bed 2 replanted and bark-mulched",
          },
          {
            id: "jul-2026-kentia",
            area: "house",
            src: "images/house-plants/jul-2026/kentia-palm-hallway-hero.webp",
            caption: "The hallway Kentia palm joins the notebook",
          },
        ],
        events: [
          {
            id: "jul-2026-stone-replant",
            type: "work",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "Late July 2026",
            area: "back",
            title: "Stone Bed replanted",
            note: "The gravel bed was rebuilt around 22 plants: hardy houseleeks and stonecrops, Ajugas, alpine flowers, grasses, Hydrangea and two tender Echeverias.",
            zoneKey: "stone",
          },
          {
            id: "jul-2026-echeveria-planted",
            type: "planted",
            date: "2026-07-28",
            datePrecision: "day",
            dateLabel: "28 July 2026",
            area: "back",
            title: "Echeveria planted",
            note: "The broad silver-grey rosette went into the Stone Bed; its Perle von Nürnberg identity remains a visible best-fit assumption.",
            plantId: "stone-echeveria",
            zoneKey: "stone",
          },
          {
            id: "jul-2026-lavender-out",
            type: "removed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Lavender went out",
            note: "The old lavender had a rotten crown and was removed. Its before photographs stay in the archive.",
            location: "Stone Bed",
            zoneKey: "stone",
          },
          {
            id: "jul-2026-hebe-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Hebe moved",
            note: "The variegated Hebe left the dry gravel planting and began re-establishing in the lower section of Flower Bed 2.",
            plantId: "stone-hebe",
            zoneKey: "bed2",
            from: "Stone Bed",
            to: "Flower Bed 2",
          },
          {
            id: "jul-2026-avens-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Avens moved",
            note: "The orange-flowered Avens moved out from beneath the Bed 1 canopy and into the lower planting of Flower Bed 2.",
            plantId: "bed2-avens",
            zoneKey: "bed2",
            from: "Flower Bed 1",
            to: "Flower Bed 2",
          },
          {
            id: "jul-2026-celosia-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Celosia moved",
            note: "The purple, yellow and red Celosia moved from Bed 1 to the front of the newly planted apple-tree bed.",
            plantId: "bed4-celosia",
            zoneKey: "bed4",
            from: "Flower Bed 1",
            to: "Flower Bed 4",
          },
          {
            id: "jul-2026-lobelia-pot-in",
            type: "planted",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "The Lobelia Pot arrived",
            note: "Starship Scarlet Bronze Leaf filled its own blue pot at the steps with dark foliage and upright scarlet spikes.",
            plantId: "lobeliapot-lobelia-starship-scarlet-bronze-leaf",
            zoneKey: "lobeliapot",
          },
          {
            id: "jul-2026-bed5-pruned",
            type: "work",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Bed 5 opened up",
            note: "The Wisteria was pruned and the base cleared, opening the trellis and rose back up around the new planted pots.",
            zoneKey: "bed5",
          },
          {
            id: "jul-2026-front-bed2-change",
            type: "work",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Front Bed 2 refreshed",
            note: "The small bed was replanted and bark-mulched. Polemonium Golden Feathers replaced Begonia Cocktail Gin beside the Coprosmas and Hebe.",
            plantId: "frontBed2-polemonium-golden-feathers",
            zoneKey: "frontBed2",
          },
          {
            id: "jul-2026-front-begonia-out",
            type: "removed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Begonia Cocktail Gin went out",
            note: "The former Front Bed 2 Begonia remains visible in the archived photographs but is no longer in the active bed.",
            location: "Front Bed 2",
            zoneKey: "frontBed2",
          },
          {
            id: "jul-2026-dogwood-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Dogwood moved to the front",
            note: "The variegated dogwood moved from the back garden into the long house-wall bed beneath the windows.",
            plantId: "bed2-variegated-dogwood",
            zoneKey: "frontBed3",
            from: "Flower Bed 2",
            to: "Front Bed 3",
          },
          {
            id: "jul-2026-red-hot-poker-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Red Hot Poker moved",
            note: "The established Kniphofia moved from the back garden to join the dogwood and climbing roses in Front Bed 3.",
            plantId: "bed1-red-hot-poker",
            zoneKey: "frontBed3",
            from: "Flower Bed 1",
            to: "Front Bed 3",
          },
          {
            id: "jul-2026-front-fern-out",
            type: "removed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "The former fern went out",
            note: "The fern beneath the front windows was removed as Front Bed 3 was reorganised. A photograph keeps its place in the record.",
            location: "Front Bed 3",
            zoneKey: "frontBed3",
          },
          {
            id: "jul-2026-front-bed4-work",
            type: "planted",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Front Bed 4 replanted",
            note: "Two climbing roses and a new mix of shrubs, grasses and perennials began a fuller wall-and-corner planting.",
            zoneKey: "frontBed4",
          },
          {
            id: "jul-2026-front-bed5-work",
            type: "planted",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Front Bed 5 filled out",
            note: "Heathers, Ceratostigma, Hypericum, Sollya, Hebe, Salvia and other new planting joined the established boundary shrubs and climbers.",
            zoneKey: "frontBed5",
          },
          {
            id: "jul-2026-front-survey",
            type: "photographed",
            date: "2026-07-25",
            datePrecision: "day",
            dateLabel: "25 July 2026",
            area: "front",
            title: "Front garden survey photographed",
            note: "The beds, fruit trees, gateway tree, retained labels and close identification details received a proper photographic record.",
            zoneKey: "frontBed5",
          },
          {
            id: "jul-2026-kentia-recorded",
            type: "photographed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "house",
            title: "Hallway palm recorded",
            note: "The grouped hallway specimen received its first full photo and condition baseline; Kentia remains a visibly assumed identification.",
            plantId: "house-hallway-kentia-palm",
            zoneKey: "houseHallKentia",
          },
        ],
      },
      {
        id: "jun-2026",
        year: 2026,
        month: 6,
        label: "June 2026",
        title: "New beds, new colour",
        note: "The first proper round of changes: new summer colour went in, the apple-tree bed was replanted, and several plants moved into places where they could make more of themselves.",
        photos: [
          {
            id: "jun-2026-bed3",
            area: "back",
            src: "images/june-2026-updates/bed3-after-wide-1.webp",
            caption: "Bed 3 after its June replant",
          },
          {
            id: "jun-2026-bed4",
            area: "back",
            src: "images/june-2026-updates/callistemon-inferno-1.webp",
            caption: "Callistemon Inferno in the apple-tree bed",
          },
          {
            id: "jun-2026-front-pot",
            area: "front",
            src: "images/june-2026-updates/front-pot-overview.webp",
            caption: "The new Front Pot summer display",
          },
          {
            id: "jun-2026-dahlia",
            area: "back",
            src: "images/june-2026-updates/dahlia-black-yellow-1.webp",
            caption: "Double Dreamy Gold arrives in Bed 1",
          },
        ],
        events: [
          {
            id: "jun-2026-bed3-replant",
            type: "work",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Flower Bed 3 replanted",
            note: "The wall-gap border was given its own identity with Kerria, Forget-me-not, Centaurea Snowy Owl and three Spiraea shrubs.",
            zoneKey: "bed3",
          },
          {
            id: "jun-2026-bed4-replant",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Apple-tree bed replanted",
            note: "Callistemon Inferno, Achillea, Gaillardia and Abelia Kaleidoscope formed a new underplanting around the established tree.",
            plantId: "bed4-callistemon-inferno-yanferno",
            zoneKey: "bed4",
          },
          {
            id: "jun-2026-dahlia-in",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Double Dreamy Gold went in",
            note: "A second compact, dark-leaved Dahlia joined the centre of Bed 1, this time with golden-yellow flowers.",
            plantId: "bed1-dahlia-yellow",
            zoneKey: "bed1",
          },
          {
            id: "jun-2026-hosta-moved",
            type: "moved",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Gold Hosta moved",
            note: "The gold-leaved Hosta moved into the shelter of Bed 1 beneath the Japanese maple canopy.",
            plantId: "bed1-hosta-gold",
            zoneKey: "bed1",
            from: "Flower Bed 2",
            to: "Flower Bed 1",
          },
          {
            id: "jun-2026-little-heath-in",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Little Heath border planted",
            note: "Seven pale-edged Pieris plants formed a repeated low border along the front of Bed 1.",
            plantId: "bed1-little-heath",
            zoneKey: "bed1",
          },
          {
            id: "jun-2026-front-pot-in",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "front",
            title: "Front Pot planted",
            note: "Two Gazanias, Calibrachoa and Bacopa White created a bright new display on the front-garden gravel.",
            plantId: "frontpot-gazania-sunny-side-up",
            zoneKey: "frontpot",
          },
          {
            id: "jun-2026-photo-round",
            type: "photographed",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "The summer growth was recorded",
            note: "Fresh bed overviews and close plant portraits captured the maple canopy, flowers, foliage and the new planting while it settled in.",
            zoneKey: "bed1",
          },
        ],
      },
      {
        id: "may-2026",
        year: 2026,
        month: 5,
        label: "May 2026",
        title: "The first pages",
        note: "This is where the garden journal really begins: a spring baseline of the established beds, pots, trees and patio before the summer changes started.",
        photos: [
          {
            id: "may-2026-bed1",
            area: "back",
            src: "images/may-2026/bed1.jpg",
            caption: "Bed 1 beneath the Japanese maple",
          },
          {
            id: "may-2026-stone",
            area: "back",
            src: "images/may-2026/stone-bed-wide.jpg",
            caption: "The original Stone Bed planting",
          },
          {
            id: "may-2026-patio",
            area: "back",
            src: "images/may-2026/patio-clematis.jpg",
            caption: "Clematis montana on the patio wall",
          },
        ],
        events: [
          {
            id: "may-2026-back-baseline",
            type: "baseline",
            date: "2026-05",
            datePrecision: "month",
            dateLabel: "May 2026",
            area: "back",
            title: "Back garden baseline recorded",
            note: "The five beds, Stone Bed, patio, steps, fruit tree and planted pots were mapped as the starting point for the Oak Lodge notebook.",
          },
          {
            id: "may-2026-established-planting",
            type: "baseline",
            date: "2026-05",
            datePrecision: "month",
            dateLabel: "May 2026",
            area: "back",
            title: "Established planting noted",
            note: "The Japanese maple, Fatsia, Rhododendron, fruit trees, Wisteria, roses and wall climbers were recorded as established before the journal.",
            zoneKey: "bed1",
          },
          {
            id: "may-2026-first-photos",
            type: "photographed",
            date: "2026-05",
            datePrecision: "month",
            dateLabel: "May 2026",
            area: "back",
            title: "First monthly photographs",
            note: "Wide views and close details created the visual baseline that later before-and-after pages can return to.",
          },
        ],
      },
    ],
  };
})();
