// Oak Lodge Garden — visual change journal
// Explicit history only: do not derive events from the current plant inventory.

(() => {
  const OAK = window.OAK = window.OAK || {};

  OAK.JOURNAL = {
    version: 1,
    entries: [
{
      "id": "oct-2026",
      "year": 2026,
      "month": 10,
      "label": "October 2026",
      "title": "Birthday plants inside and a fresh border reshuffle",
      "note": "Five birthday houseplants joined the notebook: Rhipsalis, Dracaena Bicolour Touffe, Crassula Hottentot, Philodendron and Zamioculcas. Out in the garden, Petite Star Hydrangea took Polar Passion’s place in Front Bed 4. Polar Passion moved into the old Gaillardia pocket in Back Bed 4, while Gaillardia and Wisley Vanilla Nemesia moved to Back Bed 1. Pineapple Crush Viola added new colour at the front of Back Bed 4. I also binned the Fuchsia and fern rescued from the hanging basket in September, and filled their Back Bed 1 spot with Pernettya Pink and Solanum Jupiter.",
      "photos": [
            {
                  "id": "oct-2026-rhipsalis-photo",
                  "area": "house",
                  "src": "images/oct-2026/house-rhipsalis.webp",
                  "caption": "New hanging Rhipsalis beside the sitting-room stairs"
            },
            {
                  "id": "oct-2026-petite-star-photo",
                  "area": "front",
                  "src": "images/oct-2026/front-bed4-hydrangea-petite-star-1.webp",
                  "caption": "Petite Star in Polar Passion’s former Front Bed 4 pocket"
            },
            {
                  "id": "oct-2026-back-bed1-photo",
                  "area": "back",
                  "src": "images/oct-2026/back-bed1-berry-planting.webp",
                  "caption": "Pernettya Pink and Solanum Jupiter in the cleared Back Bed 1 pocket"
            },
            {
                  "id": "oct-2026-back-bed4-photo",
                  "area": "back",
                  "src": "images/oct-2026/back-bed4-update.webp",
                  "caption": "Back Bed 4 with Polar Passion and the new Viola"
            }
      ],
      "events": [
{
  "id": "oct-2026-fuchsia-removed",
  "type": "removed",
  "date": "2026-10",
  "datePrecision": "month",
  "dateLabel": "October 2026",
  "area": "back",
  "title": "Fuchsia removed from Back Bed 1",
  "note": "Binned the unidentified Fuchsia saved from Hanging Basket 3 in September.",
  "zoneKey": "bed1",
  "location": "Back Bed 1 · beneath the Japanese Maple"
},
{
  "id": "oct-2026-fern-removed",
  "type": "removed",
  "date": "2026-10",
  "datePrecision": "month",
  "dateLabel": "October 2026",
  "area": "back",
  "title": "Fern removed from Back Bed 1",
  "note": "Binned the unidentified fern saved from Hanging Basket 3 in September.",
  "zoneKey": "bed1",
  "location": "Back Bed 1 · beneath the Japanese Maple"
},
{
  "id": "oct-2026-bed1-pernettya-pink",
  "type": "planted",
  "date": "2026-10",
  "datePrecision": "month",
  "dateLabel": "October 2026",
  "area": "back",
  "title": "Pernettya Pink planted in Back Bed 1",
  "note": "Added in the spot freed by the discarded Fuchsia and fern. Pink-fruited form; exact cultivar unresolved.",
  "zoneKey": "bed1",
  "location": "Back Bed 1 · beneath the Japanese Maple",
  "plantId": "bed1-pernettya-pink"
},
{
  "id": "oct-2026-bed1-solanum-jupiter",
  "type": "planted",
  "date": "2026-10",
  "datePrecision": "month",
  "dateLabel": "October 2026",
  "area": "back",
  "title": "Solanum Jupiter planted in Back Bed 1",
  "note": "Added in the spot freed by the discarded Fuchsia and fern. Jupiter is the supplied name.",
  "zoneKey": "bed1",
  "location": "Back Bed 1 · beneath the Japanese Maple",
  "plantId": "bed1-solanum-jupiter"
},
            {
                  "id": "oct-2026-house-sitting-rhipsalis",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "house",
                  "title": "Rhipsalis (species to confirm) added",
                  "note": "Hanging beside the sitting-room stair opening · purple star. Recorded in the October birthday photographs.",
                  "plantId": "house-sitting-rhipsalis",
                  "zoneKey": "houseSittingRhipsalis",
                  "location": "Ground floor · Hanging beside the sitting-room stair opening · purple star"
            },
            {
                  "id": "oct-2026-house-sitting-dracaena-bicolour",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "house",
                  "title": "Dracaena Bicolour Touffe added",
                  "note": "Beside the split-level stair opening · green star. Recorded in the October birthday photographs.",
                  "plantId": "house-sitting-dracaena-bicolour",
                  "zoneKey": "houseSittingDracaena",
                  "location": "Ground floor · Beside the split-level stair opening · green star"
            },
            {
                  "id": "oct-2026-house-landing-crassula-hottentot",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "house",
                  "title": "Crassula 'Hottentot' added",
                  "note": "Landing shelf above the split-level stair · orange star. Recorded in the October birthday photographs.",
                  "plantId": "house-landing-crassula-hottentot",
                  "zoneKey": "houseLandingCrassula",
                  "location": "Ground floor · Landing shelf above the split-level stair · orange star"
            },
            {
                  "id": "oct-2026-house-kitchen-philodendron",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "house",
                  "title": "Philodendron (species to confirm) added",
                  "note": "Kitchen / dining window · red star. Recorded in the October birthday photographs.",
                  "plantId": "house-kitchen-philodendron",
                  "zoneKey": "houseKitchenPhilodendron",
                  "location": "Ground floor · Kitchen / dining window · red star"
            },
            {
                  "id": "oct-2026-house-landing-zamioculcas",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "house",
                  "title": "Zamioculcas added",
                  "note": "Landing beside Bedroom 3 and the split-level stairs · blue star. Recorded in the October birthday photographs.",
                  "plantId": "house-landing-zamioculcas",
                  "zoneKey": "houseLandingZamioculcas",
                  "location": "Ground floor · Landing beside Bedroom 3 and the split-level stairs · blue star"
            },
            {
                  "id": "oct-2026-petite-star",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "front",
                  "title": "Hydrangea Petite Star planted",
                  "note": "New Petite Star planted in Polar Passion’s former Front Bed 4 position.",
                  "plantId": "frontBed4-hydrangea-petite-star",
                  "zoneKey": "frontBed4",
                  "location": "Front Bed 4"
            },
            {
                  "id": "oct-2026-nemesia-moved",
                  "type": "moved",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "back",
                  "title": "Wisley Vanilla moved into Back Bed 1",
                  "note": "The Nemesia moved from Back Bed 4 into Back Bed 1.",
                  "plantId": "bed5-big-pot-nemesia",
                  "zoneKey": "bed1",
                  "from": "Back Bed 4",
                  "to": "Back Bed 1"
            },
            {
                  "id": "oct-2026-gaillardia-moved",
                  "type": "moved",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "back",
                  "title": "Gaillardia Arizona Sun moved into Back Bed 1",
                  "note": "The Gaillardia moved from Back Bed 4 into Back Bed 1; the existing assumed cultivar qualification remains.",
                  "plantId": "bed4-gaillardia",
                  "zoneKey": "bed1",
                  "from": "Back Bed 4",
                  "to": "Back Bed 1"
            },
            {
                  "id": "oct-2026-polar-passion-moved",
                  "type": "moved",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "back",
                  "title": "Polar Passion moved into Back Bed 4",
                  "note": "Pieris Polar Passion moved from Front Bed 4 into Gaillardia’s former Back Bed 4 position.",
                  "plantId": "frontBed5-pieris-polar-passion",
                  "zoneKey": "bed4",
                  "from": "Front Bed 4",
                  "to": "Back Bed 4 · former Gaillardia position"
            },
            {
                  "id": "oct-2026-pineapple-crush",
                  "type": "planted",
                  "date": "2026-10",
                  "datePrecision": "month",
                  "dateLabel": "October 2026",
                  "area": "back",
                  "title": "Viola Pineapple Crush added",
                  "note": "The new Viola went into Back Bed 4, as confirmed by Brad.",
                  "plantId": "bed4-viola-pineapple-crush",
                  "zoneKey": "bed4",
                  "location": "Back Bed 4 · front edge"
            }
      ]
},
      {
        id: "sep-2026",
        year: 2026,
        month: 9,
        label: "September 2026",
        title: "Autumn containers refreshed, borders reshuffled and new trees planted",
        note: "September brought another substantial back-garden reshuffle. The failed Bed 2 Dianthus was replaced directly with Abelia 'Raspberry Profusion'; Skimmia 'Double Diamond', the Fuchsia and the fern moved into Back Bed 1; and Wisley Vanilla Nemesia moved from Bed 5 to Bed 4. Bed 5's big pot gained the former stairs Gaultheria and mixed Violas and Pansies, the white and blue stairs pots were refreshed with mixed Violas and Pansies, a new three-can cluster was made, and Hanging Basket 3 gained a second Hedera after the Fuchsia and fern moved out. The month also recorded the house-plant changes, front-garden trees and careful Honeysuckle renovation.",
        photos: [
          { id: "sep-2026-nicola-planter", area: "house", src: "images/house-plants/sep-2026/mixed-planter-overview-1.jpeg", caption: "Nicola’s gift pot: Spider Plant, Parlour Palm and Arrowhead Vine together" },
          { id: "sep-2026-bed1-moves", area: "back", src: "images/September Pots V2/Bed 1 - Skimmia & Fuchsia - 1.jpeg", caption: "Skimmia, Fuchsia and fern settled beneath the Japanese Maple in Back Bed 1" },
          { id: "sep-2026-bed2-raspberry-profusion", area: "back", src: "images/September Pots V2/Bed 2 - Abelia - 1.jpeg", caption: "Abelia 'Raspberry Profusion' directly replacing the failed Dianthus in Back Bed 2" },
          { id: "sep-2026-stairs-cans", area: "back", src: "images/September Pots V2/Stairs View From Top - 1.jpeg", caption: "The refreshed stairs pots and new mixed Viola and Pansy cans" },
        ],
        events: [
          { id: "sep-2026-gioia-recorded", type: "photographed", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "house", title: "Bird’s Nest Fern ‘Gioia’ recorded", note: "The retained plant passport confirms Asplenium antiquum ‘Gioia’; its former sitting-room position and first photo baseline were recorded.", plantId: "house-sitting-asplenium-gioia", zoneKey: "houseKitchenGioia" },
          { id: "sep-2026-nicola-mixed-planter-recorded", type: "photographed", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "house", title: "Nicola’s three-plant gift pot recorded", note: "The large sitting-room planter gifted by Katie’s mum, Nicola, was recorded as three separate specimens sharing one container: Spider Plant ‘Vittatum’, Parlour Palm and Arrowhead Vine. All three photo identifications remain visibly assumed without labels.", plantId: "house-sitting-mixed-spider-plant", zoneKey: "houseSittingMixedSpider" },
          { id: "sep-2026-gioia-moved-kitchen", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "house", title: "Bird’s Nest Fern ‘Gioia’ moved to the kitchen", note: "The Bird’s Nest Fern moved from the sitting-room garden window to the marked kitchen / dining window. Nicola’s three-plant gift pot now occupies its former sitting-room position.", plantId: "house-sitting-asplenium-gioia", zoneKey: "houseKitchenGioia", from: "Sitting Room garden-facing window", to: "Kitchen / Dining window" },
          { id: "sep-2026-staghorn-recorded", type: "photographed", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "house", title: "Nicola’s Staghorn fern recorded", note: "The large Platycerium bifurcatum, gifted by Nicola when she had no room for it, received its first Oak Lodge photo baseline.", plantId: "house-hallway-staghorn-fern", zoneKey: "houseHallStaghorn" },
          { id: "sep-2026-littlepot1-summer-display-removed", type: "removed", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Little Pot 1 summer display retired", note: "The Geranium and Petunia summer planting was removed from Little Pot 1. Its historic names, photographs and former position remain preserved in this journal.", location: "Little Pot 1, Steps", zoneKey: "littlepot1" },
          { id: "sep-2026-littlepot1-hellebore-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Helleborus Ice N' Roses Bennotta planted", note: "Helleborus Ice N' Roses Bennotta replaced the summer display in Little Pot 1.", plantId: "littlepot1-hellebore-ice-n-roses-bennotta", zoneKey: "littlepot1" },
          { id: "sep-2026-calibrachoa-pot-removed", type: "removed", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Candy House Calibrachoa removed", note: "The Calibrachoa Candy House Mix was removed from the Steps wall pot; its summer record and photograph are retained.", location: "Wall Pot 1, Steps", zoneKey: "wallpot1" },
          { id: "sep-2026-phormium-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Phormium 'Flamingo' planted", note: "Phormium 'Flamingo' replaced the removed Calibrachoa in the Steps wall pot.", plantId: "wallpot1-phormium-flamingo", zoneKey: "wallpot1" },
          { id: "sep-2026-skimmia-pot-refreshed", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Skimmia Pot refreshed for autumn", note: "Yellow Ripple ivy was reused in a hanging basket. A Skimmia 'Antarctica' and three Viola 'Rocky Purple Picotee' plants were added alongside Skimmia 'Cleopatra'.", zoneKey: "lobeliapot" },
          { id: "sep-2026-hanging-baskets-refreshed", type: "work", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Red and green hanging baskets made", note: "Red Basket 1 and green Basket 2 were made with matching compositions: Calluna, Rocky Purple Picotee Viola, Hedera, Pansy 'Fire' and Pansy 'Rose Surprise'. One ivy came from the Skimmia Pot and one was newly bought. Both hang in Patio Kitchen & Lounge.", zoneKey: "baskets" },
          { id: "sep-2026-honeysuckle-renovated", type: "work", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Patio Honeysuckle thinned and retrained", note: "Congested, dead and crossing twiggy growth was removed from the long-established Honeysuckle. Its mature twisted stems were retained as a clean trained framework beneath the eaves, ready for new shoots next season.", plantId: "stone-honeysuckle", zoneKey: "patio" },
          { id: "sep-2026-purple-basket-moved", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Purple Basket 3 moved to Decking", note: "The purple basket previously known as the Lounge Door Hanging Basket was moved to the Decking section; green Basket 2 now hangs at the Lounge Door location.", zoneKey: "basket3", from: "Lounge Door", to: "Decking" },
          { id: "sep-2026-frontbed5-viola-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "front", title: "Rocky Purple Picotee Viola added to Front Bed 5", note: "The remaining Viola 'Rocky Purple Picotee' was planted beside the Astrantia trio and Heather 'Winter Chocolate'.", plantId: "frontBed5-viola-rocky-purple-picotee", zoneKey: "frontBed5" },
          { id: "sep-2026-basket-3-refreshed", type: "work", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Hanging Basket 3 refreshed", note: "The Fuchsia and fern were retained in the Decking basket. The remaining planting was removed, then Lysimachia, Chrysanthemum and Cyclamen were added.", zoneKey: "basket3" },
          { id: "sep-2026-stairs-pots-refreshed", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "White and blue Steps pots replanted", note: "On the back-garden Steps, White Pot 1 received Yellow Ripple ivy, Skimmia 'Double Diamond' and Fire Red Pansies. Blue Pot 2 received Yellow Ripple ivy, Gaultheria and Fire Red Pansies.", location: "Steps · Pots 1 & 2", zoneKey: "stairpots" },
          { id: "sep-2026-bed2-dianthus-died", type: "removed", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Back Bed 2 Dianthus removed", note: "The Dianthus 'Leuchtfunk' at position 7 died and was removed. Its historic name and former position remain preserved in this journal.", location: "Back Bed 2 position 7", zoneKey: "bed2" },
          { id: "sep-2026-bed2-raspberry-profusion-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Abelia 'Raspberry Profusion' replaced the Dianthus", note: "Abelia × grandiflora 'Raspberry Profusion' was planted directly into the position vacated by the failed Dianthus in Back Bed 2.", plantId: "bed2-abelia-raspberry-profusion", zoneKey: "bed2" },
          { id: "sep-2026-double-diamond-moved-bed1", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Skimmia 'Double Diamond' moved into Back Bed 1", note: "The Skimmia moved from the white stairs pot into the sheltered planting beneath the Japanese Maple.", plantId: "stairpots-p1-skimmia-double-diamond", zoneKey: "bed1", from: "White Stairs Pot 1", to: "Back Bed 1" },
          { id: "sep-2026-basket-fuchsia-moved-bed1", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Hanging Basket 3 Fuchsia moved into Back Bed 1", note: "The unidentified Fuchsia moved from Hanging Basket 3 into the sheltered planting beneath the Japanese Maple.", zoneKey: "bed1", from: "Hanging Basket 3", to: "Back Bed 1" },
          { id: "sep-2026-basket-fern-moved-bed1", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Hanging Basket 3 fern moved into Back Bed 1", note: "The unidentified fern moved from Hanging Basket 3 into the sheltered planting beneath the Japanese Maple.", zoneKey: "bed1", from: "Hanging Basket 3", to: "Back Bed 1" },
          { id: "sep-2026-wisley-vanilla-moved-bed4", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Wisley Vanilla Nemesia moved into Back Bed 4", note: "The retained-label Nemesia moved from Bed 5's big pot to the front-right edge of Back Bed 4.", plantId: "bed5-big-pot-nemesia", zoneKey: "bed4", from: "Back Bed 5 big pot", to: "Back Bed 4" },
          { id: "sep-2026-gaultheria-moved-bed5", type: "moved", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Gaultheria moved into the Back Bed 5 big pot", note: "The unidentified Gaultheria moved from the blue stairs pot into Bed 5's big pot.", plantId: "stairpots-p2-gaultheria-unidentified", zoneKey: "bed5", from: "Blue Stairs Pot 2", to: "Back Bed 5 big pot" },
          { id: "sep-2026-bed5-violas-pansies-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Mixed Violas and Pansies added to the Bed 5 big pot", note: "A mixed selection of Violas and Pansies was planted around the moved Gaultheria and established big-pot planting as one recorded entry.", plantId: "bed5-big-pot-violas-pansies", zoneKey: "bed5" },
          { id: "sep-2026-stairs-pots-later-refresh", type: "work", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "White and blue stairs pots refreshed again", note: "After the Skimmia and Gaultheria moved into the beds, the white pot, blue pot and one can were refreshed to contain only a mixed selection of Violas and Pansies. The three containers are recorded as one stairs entry.", plantId: "stairpots-violas-pansies-group", zoneKey: "stairpots" },
          { id: "sep-2026-three-can-cluster-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Three-can Viola and Pansy cluster added", note: "Three repurposed tomato cans were planted with a mixed selection of Violas and Pansies and recorded together as one new Steps entry.", plantId: "staircans-violas-pansies-group", zoneKey: "staircans" },
          { id: "sep-2026-basket3-later-refresh", type: "work", date: "2026-09", datePrecision: "month", dateLabel: "Later September 2026", area: "back", title: "Hanging Basket 3 gained a second Hedera", note: "The Fuchsia and fern moved into Back Bed 1 and another Hedera was added to Hanging Basket 3. Two unidentified ivy plants now trail around the retained Lysimachia, Chrysanthemum and Cyclamen.", plantId: "basket3-hedera-pair-unidentified", zoneKey: "basket3" },
          { id: "sep-2026-cercis-eternal-flame-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "front", title: "Cercis 'Eternal Flame' planted", note: "The new Cercis was planted at the red-circle position in Front Bed 3, below the Bedroom 3 window.", plantId: "frontBed3-cercis-eternal-flame", zoneKey: "frontBed3" },
          { id: "sep-2026-arbutus-unedo-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "front", title: "Arbutus unedo planted", note: "The evergreen Strawberry Tree was planted at the purple-circle position beside the skinny brick wall, between the Patio and Stone Trough.", plantId: "frontArbutus-arbutus-unedo", zoneKey: "frontArbutus" },
          { id: "sep-2026-bed4-abelia-radiance-planted", type: "planted", date: "2026-09", datePrecision: "month", dateLabel: "September 2026", area: "back", title: "Abelia 'Radiance' added to Back Bed 4", note: "Abelia × grandiflora 'Radiance' was planted in Back Bed 4 and photographed as part of the September update.", plantId: "bed4-abelia-radiance", zoneKey: "bed4" },
        ],
      },
      {
        id: "aug-2026",
        year: 2026,
        month: 8,
        label: "August 2026",
        title: "The garden changed places again",
        note: "A substantial August reshuffle changed the back beds, the pots around the steps and Front Beds 4 and 5. Late in the month the failed third Physocarpus cluster was consolidated into the two survivors, two Azaleas joined Front Bed 4, Magic Carpet and Nemesia changed beds, Jurassic Gold replaced a failed Little Devil, and the renamed Skimmia Pot was replanted. The 15 August photo audit also documented inherited and previously missed plants without forcing uncertain identities.",
        photos: [
          {
            id: "aug-2026-bed1",
            area: "back",
            src: "images/aug-2026-big-changes/bed1-overview-1.webp",
            caption: "Back Bed 1 after its August additions and moves",
          },
          {
            id: "aug-2026-bed3-magic-carpet",
            area: "back",
            src: "images/aug-2026-pot-update/bed3-spiraea-magic-carpet-1.jpeg",
            caption: "Magic Carpet added to the Bed 3 Spiraea line",
          },
          {
            id: "aug-2026-front-bed4",
            area: "front",
            src: "images/aug-2026-pot-update/front-bed4-overview-2.jpeg",
            caption: "Front Bed 4 after the late-August Azalea and Nemesia changes",
          },
          {
            id: "aug-2026-skimmia-pot",
            area: "back",
            src: "images/aug-2026-pot-update/skimmia-pot-1.jpeg",
            caption: "The renamed Skimmia Pot with Cleopatra and Yellow Ripple ivy",
          },
        ],
        events: [
          {
            id: "aug-2026-front-bed4-cluster-3-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "front",
            title: "Physocarpus Cluster 3 removed",
            note: "Cluster 3 failed apart from one Lady in Red and one Little Devil. Those survivors moved into Clusters 1 and 2; the remaining failed plants were removed and binned.",
            location: "Front Bed 4 location 6",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed4-clusters-consolidated",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "front",
            title: "Two Physocarpus clusters consolidated",
            note: "Cluster 1 now contains two Little Devils and one Lady in Red. Cluster 2 now contains two Lady in Reds and one Little Devil.",
            zoneKey: "frontBed4",
            from: "Front Bed 4 Cluster 3",
            to: "Front Bed 4 Clusters 1 and 2",
          },
          {
            id: "aug-2026-front-bed4-azaleas-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "front",
            title: "Silvester Azalea planted",
            note: "Azalea japonica 'Silvester' replaced Cluster 3 at location 6 and received dropper watering.",
            plantId: "frontBed4-azalea-silvester",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed4-azalea-lotte-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "front",
            title: "Lotte Azalea created location 16",
            note: "Azalea japonica 'Lotte' was planted at the new green-star location 16 and received dropper watering.",
            plantId: "frontBed4-azalea-lotte",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-magic-carpet-moved-bed3",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "back",
            title: "Magic Carpet moved into the Bed 3 Spiraea line",
            note: "Magic Carpet moved from Front Bed 4 location 7 into the line of Double Play Big Bang Spiraeas in Back Bed 3 and joined their sprinkler watering.",
            plantId: "frontBed4-magic-carpet",
            zoneKey: "bed3",
            from: "Front Bed 4 location 7",
            to: "Flower Bed 3 Spiraea line",
          },
          {
            id: "aug-2026-nemesia-moved-front-bed4",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "front",
            title: "Nemesia moved into Front Bed 4",
            note: "Nemesia 'Lady Penelope' moved from the blue pot into the vacated location 7 and received its own dropper.",
            plantId: "lobeliapot-nemesia-lady-penelope",
            zoneKey: "frontBed4",
            from: "Former Nemesia Pot",
            to: "Front Bed 4 location 7",
          },
          {
            id: "aug-2026-front-bed5-jurassic-gold-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "front",
            title: "Jurassic Gold fern replaced Little Devil",
            note: "The failed Little Devil at Front Bed 5 location 13 was removed and binned. Dryopteris Jurassic Gold took its place and continues to share the existing sprinkler watering method.",
            plantId: "frontBed5-fern-jurassic-gold",
            zoneKey: "frontBed5",
          },
          {
            id: "aug-2026-skimmia-pot-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "back",
            title: "The blue pot became the Skimmia Pot",
            note: "The former Nemesia Pot was renamed and replanted with Skimmia Cleopatra and trailing Hedera helix Yellow Ripple.",
            plantId: "lobeliapot-skimmia-cleopatra",
            zoneKey: "lobeliapot",
          },
          {
            id: "aug-2026-skimmia-pot-ivy-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "Late August 2026",
            area: "back",
            title: "Yellow Ripple ivy added to the Skimmia Pot",
            note: "Hedera helix Yellow Ripple was planted to trail around Skimmia Cleopatra in the renamed blue pot.",
            zoneKey: "lobeliapot",
          },
          {
            id: "aug-2026-weigela-prism-magic-carpet-confirmed",
            type: "photographed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Weigela cultivar confirmed from its label",
            note: "A retained Willowbrook Garden Centre label confirmed the Flower Bed 2 Weigela as ‘Prism Magic Carpet’, replacing the earlier assumed Briant Rubidor identification.",
            plantId: "bed2-weigela",
            zoneKey: "bed2",
          },
          {
            id: "aug-2026-front-bed4-delosperma-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Delosperma Ice Cream Mix removed",
            note: "The Delosperma Ice Cream Mix was completely removed from its Front Bed 4 pocket.",
            location: "Front Bed 4, sunny open pocket near the established canopy",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed4-calluna-trio-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Calluna Trio Mix planted in Front Bed 4",
            note: "Three Calluna plants, one from each component in the mixed trio pots, were planted together in the former Delosperma location and placed on sprinkler watering.",
            plantId: "frontBed4-calluna-trio-mix",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-photo-audit-bed2",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "back",
            title: "Bed 2 Rose and Butterfly Bush documented",
            note: "New photographs were assigned to the separate inherited Rose and established Butterfly Bush in Flower Bed 2, correcting the location names on the supplied files without inferring cultivars.",
            zoneKey: "bed2",
          },
          {
            id: "aug-2026-photo-audit-bed3-rose",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "back",
            title: "Bed 3 inherited Rose photographed",
            note: "Three photographs recorded yellow flowers, developing buds and the established woody framework. The Bed 3 Rose remains a separate generic record with no cultivar inferred.",
            plantId: "bed3-rose-inherited",
            zoneKey: "bed3",
          },
          {
            id: "aug-2026-bed3-positions-identified",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "back",
            title: "Two Bed 3 markers received assumed identities",
            note: "Position 6 was provisionally recorded as Evergreen Candytuft and position 9 as Variegated Lesser Periwinkle. The Periwinkle is also visible beneath the inherited Rose; both names remain explicitly assumed pending stronger evidence.",
            zoneKey: "bed3",
          },
          {
            id: "aug-2026-agapanthus-photographed",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "back",
            title: "Stone Bed Agapanthus photographed",
            note: "The foliage and position 9 setting were documented. The record remains generic because flowers, winter habit and a cultivar label are not yet available.",
            plantId: "stone-agapanthus",
            zoneKey: "stone",
          },
          {
            id: "aug-2026-baskets-petunia-documented",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "back",
            title: "Petunia added to the hanging-basket record",
            note: "Kitchen- and lounge-door basket photographs confirmed a generic Petunia alongside the retained Fuchsia, Bacopa, Lobelia and Verbena records.",
            zoneKey: "baskets",
          },
          {
            id: "aug-2026-zone-photo-audit",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "back",
            title: "Big Pot 1 and the hallway-window patio recorded",
            note: "New context photographs updated the Big Pot 1 and Patio galleries in their current lower-garden positions.",
            zoneKey: "patio",
          },
          {
            id: "aug-2026-front-bed4-tree-evidence",
            type: "photographed",
            date: "2026-08-15",
            datePrecision: "day",
            dateLabel: "15 August 2026",
            area: "front",
            title: "Front Bed 4 tree evidence retained",
            note: "Three photographs were stored as zone-level identification evidence. They do not confirm the current Photinia assumption, so the tree identity remains unresolved.",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-littlepot2-cleared",
            type: "removed",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Little Pot 2 cleared",
            note: "The Summer Twist Red/White Pelargonium and Purple Vein Petunia were binned and the pot was cleared for a permanent Coreopsis planting.",
            location: "Little Pot 2",
            zoneKey: "littlepot2",
          },
          {
            id: "aug-2026-coreopsis-moved",
            type: "moved",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Coreopsis moved into Little Pot 2",
            note: "The established golden Coreopsis left its smaller round pot and moved into the square blue Little Pot 2, which now sits directly west of the Echinacea pot.",
            plantId: "wallpot2-coreopsis-gold",
            zoneKey: "littlepot2",
            from: "Former Coreopsis pot on the upper stair wall",
            to: "Little Pot 2",
          },
          {
            id: "aug-2026-echinacea-planted",
            type: "planted",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Echinacea Mooodz Glory planted",
            note: "The compact white coneflower went into the Coreopsis's former blue pot and took Little Pot 1's old position on the right edge of the steps.",
            plantId: "wallpot2-echinacea-mooodz-glory",
            zoneKey: "wallpot2",
          },
          {
            id: "aug-2026-littlepot1-moved",
            type: "moved",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Little Pot 1 shifted south",
            note: "Little Pot 1 moved farther down the right edge of the steps, immediately south of the new Echinacea pot.",
            zoneKey: "littlepot1",
            from: "Right edge of the steps below Bed 4",
            to: "Farther south along the right edge of the steps",
          },
          {
            id: "aug-2026-lobelia-moved",
            type: "moved",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Lobelia moved into Bed 4",
            note: "The scarlet bronze-leaved Lobelia came out of its blue pot and was planted in the space vacated by Achillea Summer Berries.",
            plantId: "lobeliapot-lobelia-starship-scarlet-bronze-leaf",
            zoneKey: "bed4",
            from: "Blue Lobelia Pot beside Bed 4",
            to: "Flower Bed 4",
          },
          {
            id: "aug-2026-cercis-added",
            type: "planted",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Carolina Sweetheart Cercis added",
            note: "A potted Cercis canadensis 'Carolina Sweetheart' took over the Lobelia Pot's former corner, bringing maroon, cream, green and pink heart-shaped foliage to the steps.",
            plantId: "cercispot-cercis-carolina-sweetheart",
            zoneKey: "cercispot",
          },
          {
            id: "aug-2026-bigpot1-moved",
            type: "moved",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "Big Pot 1 tucked into the decking corner",
            note: "The large mixed blue pot moved tightly into the upper-left corner of the decking below the Stone Bed.",
            zoneKey: "bigpot1",
            from: "Upper part of the decking",
            to: "Upper-left decking corner",
          },
          {
            id: "aug-2026-bed1-angel-wings-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Bed 1 Angel Wings removed",
            note: "The Angel Wings in Back Bed 1 was removed and binned.",
            location: "Flower Bed 1",
            zoneKey: "bed1",
          },
          {
            id: "aug-2026-bed2-angel-wings-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Bed 2 Angel Wings removed",
            note: "The second Angel Wings was removed from Back Bed 2 and binned.",
            location: "Flower Bed 2",
            zoneKey: "bed2",
          },
          {
            id: "aug-2026-nemesia-lady-penelope-moved",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Unrecorded Nemesia moved into the blue pot",
            note: "The previously missed Nemesia from Bed 1 moved into the Lobelia's former pot. Its Lady Penelope identification is recorded as an assumed best fit rather than a label confirmation.",
            plantId: "lobeliapot-nemesia-lady-penelope",
            zoneKey: "lobeliapot",
            from: "Flower Bed 1",
            to: "Nemesia Pot south of the Cercis",
          },
          {
            id: "aug-2026-aroma-heart-of-gold-moved",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Aroma Heart of Gold moved to Bed 5",
            note: "Nemesia 'Aroma Heart of Gold' moved from Bed 1 into the big mixed pot in Bed 5.",
            plantId: "bed1-nemesia",
            zoneKey: "bed5",
            from: "Flower Bed 1",
            to: "Bed 5 big pot",
          },
          {
            id: "aug-2026-bed1-abelia-added",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Another Abelia Kaleidoscope added",
            note: "A second Abelia 'Kaleidoscope' joined the planting in Back Bed 1.",
            plantId: "bed1-abelia-kaleidoscope",
            zoneKey: "bed1",
          },
          {
            id: "aug-2026-bed1-pieris-added",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Another Pieris Forest Flame added",
            note: "A second label-confirmed Pieris 'Forest Flame' was planted in Back Bed 1.",
            plantId: "bed1-pieris-forest-flame",
            zoneKey: "bed1",
          },
          {
            id: "aug-2026-sedum-rose-carpet-added",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Sedum Rose Carpet planted",
            note: "Label-confirmed Sedum 'Rose Carpet' was planted at position 1 in Bed 3.",
            plantId: "bed2-sedum-rose-carpet",
            zoneKey: "bed3",
          },
          {
            id: "aug-2026-bed23-wall-pot-added",
            type: "work",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "A new pot joined the Bed 2 and Bed 3 wall",
            note: "A new pot was placed on the brick wall shared by the west edge of Bed 2 and east edge of Bed 3.",
            location: "Shared wall between Flower Beds 2 and 3",
            zoneKey: "bed23wallpot",
          },
          {
            id: "aug-2026-lisarose-and-vinca-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Lisarose and Illumination planted together",
            note: "Viburnum 'Lisarose' and a new Vinca minor 'Illumination' were planted in the shared-wall pot. The established Vinca remains in the Bed 5 big pot.",
            zoneKey: "bed23wallpot",
          },
          {
            id: "aug-2026-viburnum-spirit-added",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Viburnum tinus Spirit added",
            note: "Label-confirmed Viburnum tinus Spirit was planted in a new pot positioned where the Lobelia had stood beside Bed 4.",
            plantId: "viburnumpot-viburnum-tinus-spirit",
            zoneKey: "viburnumpot",
          },
          {
            id: "aug-2026-achillea-moved-front-bed4",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Achillea Summer Berries moved to Front Bed 4",
            note: "The established Achillea left Back Bed 4 and was replanted in Front Bed 4.",
            plantId: "bed4-achillea",
            zoneKey: "frontBed4",
            from: "Back Flower Bed 4",
            to: "Front Bed 4",
          },
          {
            id: "aug-2026-front-bed4-old-lady-in-reds-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Two Lady in Reds removed",
            note: "Both of the original Lady in Red ninebarks were removed and binned before the Front Bed 4 cluster layout was rebuilt.",
            location: "Front Bed 4",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed4-purple-gem-moved",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Purple Gem moved within Front Bed 4",
            note: "Purple Gem moved out of its former position into one of the spaces left by the removed Lady in Reds.",
            plantId: "frontBed4-purple-gem",
            zoneKey: "frontBed4",
            from: "Ivy corner in Front Bed 4",
            to: "Former Lady in Red position in Front Bed 4",
          },
          {
            id: "aug-2026-front-bed4-physocarpus-clusters-created",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Three Physocarpus clusters created",
            note: "Two new Little Devils and three new Lady in Reds joined the retained Little Devils. Cluster 1 contains two Little Devils, Cluster 2 contains two Lady in Reds, and Cluster 3 contains two Little Devils with one Lady in Red.",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed4-rhododendron-libretto-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Rhododendron Libretto planted",
            note: "Rhododendron 'Libretto' was added as a broad evergreen flowering anchor in the sheltered brick corner of Front Bed 4.",
            plantId: "frontBed4-rhododendron-libretto",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed5-little-devil-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Spare Little Devil added to Front Bed 5",
            note: "A spare compact Little Devil ninebark was planted among the Front Bed 5 shrubs.",
            zoneKey: "frontBed5",
          },
          {
            id: "aug-2026-front-bed4-astrantia-moved",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Astrantia trio moved to Front Bed 5",
            note: "The named Buckland, Claret and Star of Love Astrantias moved together from the open centre of Front Bed 4 into a wall-side pocket in Front Bed 5.",
            plantId: "frontBed4-astrantia-trio",
            zoneKey: "frontBed5",
            from: "Front Bed 4",
            to: "Front Bed 5",
          },
          {
            id: "aug-2026-pieris-swapped-beds",
            type: "moved",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "The two Pieris swapped beds",
            note: "Pieris 'Flaming Silver' moved from Front Bed 4 to Front Bed 5, while Pieris 'Polar Passion' moved into Flaming Silver's former Front Bed 4 position.",
            plantId: "frontBed5-pieris-polar-passion",
            zoneKey: "frontBed4",
            from: "Front Bed 5",
            to: "Front Bed 4",
          },
          {
            id: "aug-2026-front-bed4-dahlia-tampico-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Dahlia Tampico planted",
            note: "The red-and-white Dahlia Dalina Maxi 'Tampico' was added to the open front-right section of Front Bed 4.",
            plantId: "frontBed4-dahlia-tampico",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed4-verbena-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Margaret's Memory Verbena planted",
            note: "Verbena 'Margaret's Memory' was planted at the sunny front edge of Front Bed 4 beside the new Dahlia.",
            plantId: "frontBed4-verbena-margarets-memory",
            zoneKey: "frontBed4",
          },
          {
            id: "aug-2026-front-bed5-honeysuckle-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Front Bed 5 Honeysuckle removed",
            note: "The established Honeysuckle was removed from its boundary support. Its July photograph remains in the archive.",
            location: "Front Bed 5",
            zoneKey: "frontBed5",
          },
          {
            id: "aug-2026-front-bed5-hydrangea-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Hydrangea Bloody Marie planted",
            note: "Hydrangea paniculata Bloody Marie was planted in the Honeysuckle's former position, with cream panicles already ageing pink.",
            plantId: "frontBed5-hydrangea-bloody-marie",
            zoneKey: "frontBed5",
          },
          {
            id: "aug-2026-front-bed5-euphorbia-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Euphorbia Ascot Petite planted",
            note: "The compact evergreen Euphorbia 'Ascot Petite' went into Polar Passion's former position in Front Bed 5.",
            plantId: "frontBed5-euphorbia-ascot-petite",
            zoneKey: "frontBed5",
          },
          {
            id: "aug-2026-celosia-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Celosias removed",
            note: "The red, purple and yellow Celosias were removed from Bed 4.",
            location: "Flower Bed 4",
            zoneKey: "bed4",
          },
          {
            id: "aug-2026-forget-me-not-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Forget-me-not removed",
            note: "The Forget-me-not was removed from Flower Bed 3.",
            location: "Flower Bed 3",
            zoneKey: "bed3",
          },
          {
            id: "aug-2026-city-knights-planted",
            type: "planted",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Coprosma City Knights joined Front Bed 2",
            note: "The label-confirmed dark burgundy Coprosma was planted against the hedge, completing a trio of glossy foliage shrubs in the small front-door bed.",
            plantId: "frontBed2-coprosma-city-knights",
            zoneKey: "frontBed2",
          },
          {
            id: "aug-2026-front-bed5-cherry-laurel-removed",
            type: "removed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "Front Bed 5 Cherry Laurel removed",
            note: "The established Cherry Laurel was physically removed from the boundary bed. Its historical name and former Front Bed 5 location remain recorded here.",
            location: "Front Bed 5",
            zoneKey: "frontBed5",
          },
          {
            id: "aug-2026-front-pots-photographed",
            type: "photographed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "The boundary pots were documented",
            note: "A new overview recorded P1, the mixed seasonal pot on the left, and P2, the Fuchsia pot on the right, between Front Bed 5 and the Fruit Trees.",
            location: "Front Pots",
            zoneKey: "frontPots",
          },
          {
            id: "aug-2026-stone-bed-map-reconciled",
            type: "work",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "back",
            title: "Stone Bed positions reconciled",
            note: "The final 1–22 Stone Bed layout was recorded. Agapanthus was added at position 9 with photographs still required, and the Cabbage Tree was correctly located in Bed 5.",
            plantId: "stone-agapanthus",
            zoneKey: "stone",
          },
          {
            id: "aug-2026-photo-update",
            type: "photographed",
            date: "2026-08-02",
            datePrecision: "day",
            dateLabel: "2 August 2026",
            area: "back",
            title: "The August changes were photographed",
            note: "New photographs recorded the wider August reshuffle, including Beds 1, 2, 4 and 5 and the new wall and Viburnum pots.",
            location: "Back garden",
          },
          {
            id: "aug-2026-front-small-changes-photographed",
            type: "photographed",
            date: "2026-08",
            datePrecision: "month",
            dateLabel: "August 2026",
            area: "front",
            title: "The smaller front-garden changes were photographed",
            note: "New overview and plant photographs recorded the Front Bed 4 and 5 moves, additions and the Honeysuckle replacement.",
            location: "Front Beds 4 and 5",
          },
        ],
      },
      {
        id: "jul-2026",
        year: 2026,
        month: 7,
        label: "July 2026",
        title: "The garden changed shape",
        note: "A big month at Oak Lodge. The Stone Bed became a proper alpine and succulent garden, plants found better homes across the back and front, and I finally recorded the house palm too.",
        photos: [
          {
            id: "jul-2026-stone-before",
            area: "back",
            src: "images/jul-2026/stone-bed-before-lavender-removal-1.webp",
            caption: "Stone Bed before the late-July replant",
            badge: "before",
            pair: "stone-july",
          },
          {
            id: "jul-2026-stone-after",
            area: "back",
            src: "images/jul-2026/stone-bed-after-replanting-1.webp",
            caption: "The new alpine and succulent planting",
            badge: "after",
            pair: "stone-july",
          },
          {
            id: "jul-2026-front-bed2",
            area: "front",
            src: "images/jul-2026/front-bed2-after-bark-1.webp",
            caption: "Front Bed 2 replanted and bark-mulched",
          },
          {
            id: "jul-2026-kentia",
            area: "house",
            src: "images/house-plants/jul-2026/kentia-palm-hallway-hero.webp",
            caption: "The hallway Kentia palm joins the notebook",
          },
        ],
        events: [
          {
            id: "jul-2026-stone-replant",
            type: "work",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "Late July 2026",
            area: "back",
            title: "Stone Bed replanted",
            note: "The gravel bed was rebuilt around 22 plants: hardy houseleeks and stonecrops, Ajugas, alpine flowers, grasses, Hydrangea and two tender Echeverias.",
            zoneKey: "stone",
          },
          {
            id: "jul-2026-echeveria-planted",
            type: "planted",
            date: "2026-07-28",
            datePrecision: "day",
            dateLabel: "28 July 2026",
            area: "back",
            title: "Echeveria planted",
            note: "The broad silver-grey rosette went into the Stone Bed; its Perle von Nürnberg identity remains a visible best-fit assumption.",
            plantId: "stone-echeveria",
            zoneKey: "stone",
          },
          {
            id: "jul-2026-lavender-out",
            type: "removed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Lavender went out",
            note: "The old lavender had a rotten crown and was removed. Its before photographs stay in the archive.",
            location: "Stone Bed",
            zoneKey: "stone",
          },
          {
            id: "jul-2026-avens-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Avens moved",
            note: "The orange-flowered Avens moved out from beneath the Bed 1 canopy and into the lower planting of Flower Bed 2.",
            plantId: "bed2-avens",
            zoneKey: "bed2",
            from: "Flower Bed 1",
            to: "Flower Bed 2",
          },
          {
            id: "jul-2026-celosia-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Celosia moved",
            note: "The purple, yellow and red Celosia moved from Bed 1 to the front of the newly planted apple-tree bed.",
            zoneKey: "bed4",
            from: "Flower Bed 1",
            to: "Flower Bed 4",
          },
          {
            id: "jul-2026-lobelia-pot-in",
            type: "planted",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "The Lobelia Pot arrived",
            note: "Starship Scarlet Bronze Leaf filled its own blue pot at the steps with dark foliage and upright scarlet spikes.",
            plantId: "lobeliapot-lobelia-starship-scarlet-bronze-leaf",
            zoneKey: "lobeliapot",
          },
          {
            id: "jul-2026-bed5-pruned",
            type: "work",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "back",
            title: "Bed 5 opened up",
            note: "The Wisteria was pruned and the base cleared, opening the trellis and rose back up around the new planted pots.",
            zoneKey: "bed5",
          },
          {
            id: "jul-2026-front-bed2-change",
            type: "work",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Front Bed 2 refreshed",
            note: "The small bed was replanted and bark-mulched. Polemonium Golden Feathers replaced Begonia Cocktail Gin beside the Coprosmas and Hebe.",
            plantId: "frontBed2-polemonium-golden-feathers",
            zoneKey: "frontBed2",
          },
          {
            id: "jul-2026-front-begonia-out",
            type: "removed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Begonia Cocktail Gin went out",
            note: "The former Front Bed 2 Begonia remains visible in the archived photographs but is no longer in the active bed.",
            location: "Front Bed 2",
            zoneKey: "frontBed2",
          },
          {
            id: "jul-2026-dogwood-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Dogwood moved to the front",
            note: "The variegated dogwood moved from the back garden into the long house-wall bed beneath the windows.",
            plantId: "bed2-variegated-dogwood",
            zoneKey: "frontBed3",
            from: "Flower Bed 2",
            to: "Front Bed 3",
          },
          {
            id: "jul-2026-red-hot-poker-moved",
            type: "moved",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Red Hot Poker moved",
            note: "The established Kniphofia moved from the back garden to join the dogwood and climbing roses in Front Bed 3.",
            plantId: "bed1-red-hot-poker",
            zoneKey: "frontBed3",
            from: "Flower Bed 1",
            to: "Front Bed 3",
          },
          {
            id: "jul-2026-front-fern-out",
            type: "removed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "The former fern went out",
            note: "The fern beneath the front windows was removed as Front Bed 3 was reorganised. A photograph keeps its place in the record.",
            location: "Front Bed 3",
            zoneKey: "frontBed3",
          },
          {
            id: "jul-2026-front-bed4-work",
            type: "planted",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Front Bed 4 replanted",
            note: "Two climbing roses and a new mix of shrubs, grasses and perennials began a fuller wall-and-corner planting.",
            zoneKey: "frontBed4",
          },
          {
            id: "jul-2026-front-bed5-work",
            type: "planted",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "front",
            title: "Front Bed 5 filled out",
            note: "Heathers, Ceratostigma, Hypericum, Sollya, Hebe, Salvia and other new planting joined the established boundary shrubs and climbers.",
            zoneKey: "frontBed5",
          },
          {
            id: "jul-2026-front-survey",
            type: "photographed",
            date: "2026-07-25",
            datePrecision: "day",
            dateLabel: "25 July 2026",
            area: "front",
            title: "Front garden survey photographed",
            note: "The beds, fruit trees, gateway tree, retained labels and close identification details received a proper photographic record.",
            zoneKey: "frontBed5",
          },
          {
            id: "jul-2026-kentia-recorded",
            type: "photographed",
            date: "2026-07",
            datePrecision: "month",
            dateLabel: "July 2026",
            area: "house",
            title: "Hallway palm recorded",
            note: "The grouped hallway specimen received its first full photo and condition baseline; Kentia remains a visibly assumed identification.",
            plantId: "house-hallway-kentia-palm",
            zoneKey: "houseHallKentia",
          },
        ],
      },
      {
        id: "jun-2026",
        year: 2026,
        month: 6,
        label: "June 2026",
        title: "New beds, new colour",
        note: "The first proper round of changes: new summer colour went in, the apple-tree bed was replanted, and several plants moved into places where they could make more of themselves.",
        photos: [
          {
            id: "jun-2026-bed3",
            area: "back",
            src: "images/june-2026-updates/bed3-after-wide-1.webp",
            caption: "Bed 3 after its June replant",
          },
          {
            id: "jun-2026-bed4",
            area: "back",
            src: "images/june-2026-updates/callistemon-inferno-1.webp",
            caption: "Callistemon Inferno in the apple-tree bed",
          },
          {
            id: "jun-2026-front-pot",
            area: "front",
            src: "images/june-2026-updates/front-pot-overview.webp",
            caption: "The new Front Pot summer display",
          },
          {
            id: "jun-2026-dahlia",
            area: "back",
            src: "images/june-2026-updates/dahlia-black-yellow-1.webp",
            caption: "Double Dreamy Gold arrives in Bed 1",
          },
        ],
        events: [
          {
            id: "jun-2026-bed3-replant",
            type: "work",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Flower Bed 3 replanted",
            note: "The wall-gap border was given its own identity with Kerria, Forget-me-not, Centaurea Snowy Owl and three Spiraea shrubs.",
            zoneKey: "bed3",
          },
          {
            id: "jun-2026-bed4-replant",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Apple-tree bed replanted",
            note: "Callistemon Inferno, Achillea, Gaillardia and Abelia Kaleidoscope formed a new underplanting around the established tree.",
            plantId: "bed4-callistemon-inferno-yanferno",
            zoneKey: "bed4",
          },
          {
            id: "jun-2026-dahlia-in",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Double Dreamy Gold went in",
            note: "A second compact, dark-leaved Dahlia joined the centre of Bed 1, this time with golden-yellow flowers.",
            plantId: "bed1-dahlia-yellow",
            zoneKey: "bed1",
          },
          {
            id: "jun-2026-hosta-moved",
            type: "moved",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Gold Hosta moved",
            note: "The gold-leaved Hosta moved into the shelter of Bed 1 beneath the Japanese maple canopy.",
            plantId: "bed1-hosta-gold",
            zoneKey: "bed1",
            from: "Flower Bed 2",
            to: "Flower Bed 1",
          },
          {
            id: "jun-2026-little-heath-in",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "Little Heath border planted",
            note: "Seven pale-edged Pieris plants formed a repeated low border along the front of Bed 1.",
            plantId: "bed1-little-heath",
            zoneKey: "bed1",
          },
          {
            id: "jun-2026-front-pot-in",
            type: "planted",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "front",
            title: "Front Pot planted",
            note: "Two Gazanias, Calibrachoa and Bacopa White created a bright new display on the front-garden gravel.",
            plantId: "frontpot-gazania-sunny-side-up",
            zoneKey: "frontpot",
          },
          {
            id: "jun-2026-photo-round",
            type: "photographed",
            date: "2026-06",
            datePrecision: "month",
            dateLabel: "June 2026",
            area: "back",
            title: "The summer growth was recorded",
            note: "Fresh bed overviews and close plant portraits captured the maple canopy, flowers, foliage and the new planting while it settled in.",
            zoneKey: "bed1",
          },
        ],
      },
      {
        id: "may-2026",
        year: 2026,
        month: 5,
        label: "May 2026",
        title: "The first pages",
        note: "This is where the garden journal really begins: a spring baseline of the established beds, pots, trees and patio before the summer changes started.",
        photos: [
          {
            id: "may-2026-bed1",
            area: "back",
            src: "images/may-2026/bed1.jpg",
            caption: "Bed 1 beneath the Japanese maple",
          },
          {
            id: "may-2026-stone",
            area: "back",
            src: "images/may-2026/stone-bed-wide.jpg",
            caption: "The original Stone Bed planting",
          },
          {
            id: "may-2026-patio",
            area: "back",
            src: "images/may-2026/patio-clematis.jpg",
            caption: "Clematis montana on the patio wall",
          },
        ],
        events: [
          {
            id: "may-2026-back-baseline",
            type: "baseline",
            date: "2026-05",
            datePrecision: "month",
            dateLabel: "May 2026",
            area: "back",
            title: "Back garden baseline recorded",
            note: "The five beds, Stone Bed, patio, steps, fruit tree and planted pots were mapped as the starting point for the Oak Lodge notebook.",
          },
          {
            id: "may-2026-established-planting",
            type: "baseline",
            date: "2026-05",
            datePrecision: "month",
            dateLabel: "May 2026",
            area: "back",
            title: "Established planting noted",
            note: "The Japanese maple, Fatsia, Rhododendron, fruit trees, Wisteria, roses and wall climbers were recorded as established before the journal.",
            zoneKey: "bed1",
          },
          {
            id: "may-2026-first-photos",
            type: "photographed",
            date: "2026-05",
            datePrecision: "month",
            dateLabel: "May 2026",
            area: "back",
            title: "First monthly photographs",
            note: "Wide views and close details created the visual baseline that later before-and-after pages can return to.",
          },
        ],
      },
    ],
  };
})();
