// Practical techniques shared by explicitly authored seasonal jobs. No plant
// identities or care instructions are inferred from names at runtime.
(() => {
  const OAK = window.OAK;
  OAK.SEASONAL_CATEGORIES = [
    { id: 'prune', title: 'Pruning & training', note: 'Choose the right stems, keep the framework and work in the right window.' },
    { id: 'deadhead', title: 'Deadheading & cutting back', note: 'Make room for new flowers and growth without cutting away next season.' },
    { id: 'remove', title: 'Removing finished plants', note: 'Remove only what has failed or finished; keep healthy permanent planting.' },
    { id: 'refresh', title: 'Pot & basket refresh', note: 'Keep what is thriving, refresh gaps and look after the shared root space.' },
    { id: 'plant', title: 'Planting, moving & dividing', note: 'Only when needed, with room and aftercare ready before lifting.' },
    { id: 'mulch', title: 'Mulching & feeding', note: 'Treat the root area appropriately, with crowns and trunks left clear.' },
    { id: 'protect', title: 'Frost & winter protection', note: 'Outdoor shelter is the default. Some plants still need frost-free accommodation.' },
    { id: 'check', title: 'Checks, clearing & harvest', note: 'Small seasonal checks, useful clearing and ripe fruit.' },
  ];
  OAK.SEASONAL_GUIDES = {
    prune: { tools: 'Sharp bypass secateurs; gloves; loppers only for stems within their cutting capacity.', keep: 'Healthy framework and the buds or young shoots identified in this job.', remove: 'Only the specified stems. Inspect the whole plant before the first cut.', mistake: 'Applying the same cut or height to every shrub. Flowering wood and pruning windows differ.' },
    deadhead: { tools: 'Clean snips or secateurs and a small container for clippings.', keep: 'Unopened buds, healthy leaves and any seedheads deliberately left for wildlife.', remove: 'The finished flower and the part of its stalk specified below.', mistake: 'Removing petals alone, or cutting through fresh buds beneath the old flower.' },
    clear: { tools: 'Gloves, snips and a bucket; use fingers around delicate emerging shoots.', keep: 'Firm crowns, fresh shoots, healthy basal leaves and useful standing seedheads.', remove: 'Collapsed, diseased or fully dead material that crowds living growth.', mistake: 'Treating a dormant perennial as a dead annual or cutting off healthy evergreen foliage.' },
    remove: { tools: 'Gloves, snips and a small hand fork; labels for plants being retained.', keep: 'Living perennial crowns, sound shrubs and neighbouring roots.', remove: 'Only failed seasonal plants named in the job; separate diseased debris.', mistake: 'Pulling out the whole shared root mass. Snip tangled dead stems at soil level if lifting would disturb plants being kept.' },
    refresh: { tools: 'Hand trowel, suitable peat-free compost, watering can and labels.', keep: 'Healthy permanent plants at their existing planting depth.', remove: 'Spent bedding and loose exhausted surface compost without tearing established roots.', mistake: 'Burying crowns or filling a pot so high there is no space to water. Settle new planting with water and let excess drain.' },
    plant: { tools: 'Hand fork or spade, labels, suitable compost and a watering can.', keep: 'Healthy rooted sections; replant promptly at the original depth.', remove: 'Only clearly dead centres or unwanted rooted sections, where division is actually advised.', mistake: 'Dividing a healthy young plant simply because the calendar mentions division. Work in moist, unfrozen soil and water in.' },
    mulch: { tools: 'Hand fork for weeds, bucket and suitable well-rotted mulch; feed only if specified.', keep: 'A clear space around trunks, stems and perennial crowns.', remove: 'Weeds and smothering debris before covering the soil.', mistake: 'Mulching dry or frozen ground, burying crowns, or spreading rich organic mulch across alpine rosettes.' },
    feed: { tools: 'The appropriate feed label and a measure, only when feeding is called for.', keep: 'A record of the last application and the plant’s actual growth stage.', remove: 'Unnecessary feeding reminders when growth slows.', mistake: 'Using more fertiliser to fix damage caused by cold, drought or poor drainage.' },
    protect: { tools: 'Breathable fleece, secure supports, pot feet and a local weather forecast.', keep: 'Airflow, clear drainage and healthy protective top growth.', remove: 'Sodden covers and wet debris pressing against a crown; vent covers in mild weather.', mistake: 'Assuming fleece or an unheated shelter is frost-free. Tender plants may need accommodation that is not available here.' },
    support: { tools: 'Soft garden ties, suitable stakes and secateurs for damaged ties.', keep: 'Strong stems spread over sound supports with room to thicken.', remove: 'Tight, broken or abrasive ties.', mistake: 'Pulling woody stems into sharp bends or tying so tightly that bark is pinched.' },
    check: { tools: 'Gloves, a phone for comparison photographs and a small bucket.', keep: 'Healthy growth and wildlife habitat that is not smothering plants.', remove: 'Only identified problems; record anything uncertain before acting.', mistake: 'Treating every mark as disease or every bare stem as dead. Check the plant and conditions first.' },
    harvest: { tools: 'Shallow trays and labels; work only with fruit safely reachable from the ground.', keep: 'Sound fruit for storage and selected fruit for wildlife.', remove: 'Ripe fruit without wrenching the spur; collect rotting windfalls.', mistake: 'Harvesting every tree on one date. Use the fruit’s readiness, not the month alone.' },
  };
  OAK.SEASONAL_DIAGRAMS = {
    bud: { title: 'A cut above a bud', text: 'Find a living bud pointing in the direction you want the new shoot to grow. Cut about 5mm above it, with a slight slope away. Keep the bud; do not leave a long dying stub.' },
    collar: { title: 'Keep the branch collar', text: 'The collar is the slight swelling where a branch meets its parent. Cut just outside it, not flush against the trunk. This sketch is for a small reachable branch; large or heavy limbs need appropriate equipment and skilled help.' },
    renewal: { title: 'Thin old stems; keep young ones', text: 'Trace an old, crowded stem right to the base. Remove only the proportion specified in the job, keeping the younger stems. Do not shear every stem to the same height.' },
    rose: { title: 'Train a climbing rose', text: 'Keep and loosely tie the long main canes in a fan, as close to horizontal as they comfortably bend. Prune the short flowering side shoots as described for this rose. This is not a rule for every rambler or an unidentified rose.' },
    'wisteria-winter': { title: 'Wisteria in winter', text: 'Keep the permanent main branch. Count two or three buds from the base of a side shoot shortened last summer, then cut just above the last retained bud. Do not cut off the supporting main branch.' },
    'wisteria-summer': { title: 'Wisteria in summer', text: 'On a new whippy side shoot, count five or six leaves from its origin at the main branch. Cut just beyond the last retained leaf. Keep a useful long shoot if it is needed to extend the framework.' },
    'clematis-1': { title: 'Early-flowering clematis · group 1', text: 'Montana flowers on existing growth. After flowering, shorten only an overlong shoot to a healthy side branch. Keep the main framework; do not give it the low winter cut used for group 3.' },
    'clematis-3': { title: 'Late-flowering clematis · group 3', text: 'For the recorded viticella, trace each stem from the ground and find a strong pair of buds roughly 15–30cm up. Cut just above those buds in late winter. Never apply this cut to the Patio montana.' },
    deadhead: { title: 'Follow the finished flower down', text: 'For a branching flowering stem, remove the spent head back to a healthy leaf joint or side shoot. Keep unopened buds. Plants with separate leafless flower stalks need that stalk removed near its base instead; follow the named plant’s instructions.' },
    mulch: { title: 'Mulch the soil, leave the base clear', text: 'Spread an approximately 5cm layer of well-rotted mulch over moist, weed-free border soil. Leave an open ring around the stem or crown. This is ordinary border mulching, not the thicker winter cover specified for dormant dahlia tubers.' },
  };
})();
